### ISSUE TITLE
`toEventHandler` changes handler shape

### ISSUE THREAD

**Issue by farnabaz** [unjs/h3#115]
When calling `toEventHandler` with an event handler function

```ts
toEventHandler((event) => {
})
```

It is expected that the first argument receives as `H2Event`. But in this case the shape of handler changes and first argument receives as `IncommingMessage`.

This is related to 
https://github.com/unjs/h3/blob/0692656c59074c3900b92b203151590f4ab8e055/src/event.ts#L88-L90

**Comment by pi0** [comment]
Nice naming BTW for legacy interface `H2Event` (vs `H3Event) :D

**Comment by pi0** [comment]
Checking this again, i was wrong at first I guess. Input of `toEventHandler`:

- If is an event handler (created by `eventHandler(...)`) will be returned as is
- If it is not an event handler, will be converted and `event.req` should be an extended version of `IncomingMessage` with compatibility props (event, context).

```js
app.use('/', toEventHandler((req) => {
  return req.context
}))
```

What do you expect?

**Comment by farnabaz** [comment]
This function used inside `defineCacheEventHandler`.

https://github.com/unjs/nitro/blob/cdcd35adf3e4f1d3902605f97559c0dcf6d0febf/src/runtime/cache.ts#L111

When I use it like

```
defineCacheEventHandler((event) => {

})
```

I expect that `event` argument is `H3Event` but the issue is it receives `IncommingMessage`.

**Comment by pi0** [comment]
This needed a slighly breaking change from nitro to make usage of `eventHandler` same as `cachedEventHandler`. https://github.com/unjs/nitro/commit/7e72b8f327fb0141bce32d2b0b50e357ec6a7a07
