### ISSUE TITLE
sendRedirect does not end the response

### ISSUE THREAD

**Issue by huang-julien** [unjs/h3#118]
When i was trying to make redirection on initialLoad on nuxt, i was getting a strange behavior when redirecting through a NuxtModule with the AddServerhandler helper. Using h3 sendRedirect helper did not close the response and nuxt returned a string with "Redirecting to" + path, i also had an error in the console about h3 trying to send a response after the response was already sent. Client side, i did did get the redirection html response but the header was overwritten by a 404.
[here](https://github.com/unjs/h3/blob/417af22d737832133f0d7025e29d915b11ff8881/src/utils/response.ts#L25).
Should'nt the helper close the response with a .end() ?
```ts
export function sendRedirect (event: CompatibilityEvent, location: string, code = 302) {
  return event.res.writeHead(code, {
     location
  }).end()
}
```

**Comment by YuLogun** [comment]
@huang-julien 
Hi! 
Could you please tell whether you've managed to solve this issue?

For SEO purposes I need to redirect a user from a path without a trailing slash to a path with it.

In `nuxt.config` I added a hook
```
export default defineNuxtConfig({
    router: {
        options: {
            strict: true,
        },
    },
    hooks: {
        'pages:extend'(pages) {
            for (const page of pages) {
                page.path = withTrailingSlash(page.path);
            }
        },
    },
});
```

I also created a file `server/middleware/redirect.ts` with the following code

```
export default defineEventHandler((event) => {
    const decodedBaseUrl= decodeURI(event.req.url)
    const toUrl = decodedBaseUrl.replace(new RegExp('^(\\/[^\\?]*[^\\/])(\\?.*)?$'), '$1/$2')
   
    if (decodedBaseUrl !== toUrl) {
        sendRedirect(event, toUrl, 302)
    }
})
```

In the terminal I get this error after the redirect http://joxi.ru/p27J50viLbZMkm 
What am I missing here?

**Comment by huang-julien** [comment]
well in my case, it was because i was using sendRedirect instead of navigateTo
