### ISSUE TITLE
Add useParam(event) like useQuery(event)

### ISSUE THREAD

**Issue by mik7up** [unjs/h3#120]
To access parameters need to do `event.context.params.name`.
Why not exists `useParam(event)`?

**Comment by pi0** [comment]
`useQuery` actually parses query from event object but params are already available... But I don't see any reason not to introduce `useRouterParams(event)` as syntax sugar 👍🏼

**Comment by NozomuIkuta** [comment]
@pi0 

This feature also looks as easy to implement as #147.
I will submit a PR. 🙋‍♀️
