### ISSUE TITLE
Why event and not context, req, res?

### ISSUE THREAD

**Issue by mik7up** [unjs/h3#121]
Now 

```
export default defineEventHandler(async (event) => {
    const body = await useBody(event)
    return { body }
})
```

Why not 

```
export default defineEventHandler(async ({ context, req, res }) => {
    const body = await useBody(req) // req or context or what is used here
    return { body }
})
```

Why `event.context.params.name` and not `request.params.name`?

**Comment by pi0** [comment]
There are several considerations in API design:

- Keeping `event` a generic namespace for future proof API (https://github.com/unjs/h3/issues/81)
- Keeping `event.context` as an open namespace for plugins and utils such as router to be extended
- Avoid modification of Node.js built-in `req` object nor advice to depend on it
- (from your example) Also avoid destructre `event` object as `{ context, ... }`) it is to be passed around as is consistent. Destructing prevents that and makes problem you first mention why `event.*` and not `XYZ.*` (XYZ a subkey of event)
