### ISSUE TITLE
defineEventHandler not accepting multiple handlers

### ISSUE THREAD

**Issue by notshekhar** [unjs/h3#127]

**Comment by notshekhar** [comment]
I have a naive approach to doing this, if we can somehow merge all functions in defineEventHandler's argument 
defineEventHandler function takes handler and returns handlers
if we can do this defineEventHandler(one, two, three) and returns a handler like this we can do this function one(){
    const a = 1
    console.log(a)
    return function b(){
        const a = 2
        return a
        return function c(){
            return 3
        }()
    }()
}

**Comment by notshekhar** [comment]
@pi0

**Comment by notshekhar** [comment]
@pi0 i have also written a small function to merge all the handlers
```
function mergeFunction() {
    let func = arguments[arguments.length - 1].toString()

    for (let i = arguments.length - 1; i > 0; i--) {
        const function2 = arguments[i - 1].toString()
        // replace last character }in function 2 byt function 1
        func = `${function2.substring(
            0,
            function2.length - 1
        )}\nreturn ${func}(event)}\n`
    }
    // remove string before first { and last } in string
    func = func.substring(func.indexOf("{") + 1, func.lastIndexOf("}"))
    console.log(func)
    return Function("event", func)
}
```

**Comment by notshekhar** [comment]
No its not working in nuxt

**Comment by notshekhar** [comment]
<img width="1467" alt="Screenshot 2022-06-13 at 14 06 11" src="https://user-images.
![Screenshot 2022-06-13 at 14 06 23](https://user-images.githubusercontent.com/36845555/173314356-d3dd4544-7dc3-4e7c-9a58-1999d59bc1d7.png)
githubusercontent.com/36845555/173314324-c7d980b7-0907-48e6-95df-5137afed4df8.png">

**Comment by notshekhar** [comment]
<img width="1467" alt="" src="https://user-images.githubusercontent.com/36845555/173314463-89119130-423e-43b2-96e6-db89564286dc.png">
<img width="1467" alt="" src="https://user-images.githubusercontent.com/36845555/173314554-72917d55-e522-4e66-828b-020ccbb931dc.png>

**Comment by notshekhar** [comment]
![](https://user-images.githubusercontent.com/36845555/173314765-c2a8651a-241b-4af3-9a6c-0d960b70ce33.png)

**Comment by notshekhar** [comment]
@wobsoriano

**Comment by wobsoriano** [comment]
oh the array export works only on `~/server/middleware` in nuxt

**Comment by notshekhar** [comment]
@wobsoriano  No, I want middleware on a single endpoint. `/server/middleware` and it automatically runs on every route change.

**Comment by wobsoriano** [comment]
> @wobsoriano  No, I want middleware on a single endpoint, and `/server/middleware` automatically runs on every route change.

That's why you have to conditionally check it 😉

Use server middleware > check url > continue to api url

**Comment by notshekhar** [comment]
yeah currently I am checking the URL but I might add more endpoints and every time I will add a new endpoint will have to add it in middleware condition, so I do want something to add middleware on individual endpoints like express.

**Comment by notshekhar** [comment]
@wobsoriano

**Comment by wobsoriano** [comment]
> yeah currently I am checking the URL but I might add more endpoints and every time I will add a new endpoint will have to add it in middleware condition, so I do want something to add middleware on individual endpoints like express.

Yeah that's currently the only way, or, you can create an interceptor function and use that for every api route you need

**Comment by notshekhar** [comment]
@wobsoriano can we connect, what we can do is we can also implement this in nitro.

**Comment by notshekhar** [comment]
@wobsoriano ??

**Comment by pi0** [comment]
H3 event handlers, unlike express, are not middleware runners. You probably want to split your logic into reusable composable functions that accept `event` objects.

But if you really want to use this pattern, nesting apps is possible. as @wobsoriano suggested you can create a nested app:

```js
import { eventHandler, createApp } from 'h3';

const app = createApp();

app.use([
  eventHandler((event) => {
    event.context.counter = 1;
  }),
  eventHandler((event) => {
    event.context.counter++;
  }),
  eventHandler((event) => 'Counter:' + event.context.counter),
]);

export default app;
```

Example sandbox: https://stackblitz.com/edit/github-rqbwda?file=routes%2Findex.ts

**Comment by notshekhar** [comment]
@pi0 now how to I do this it is not working anymore and I have used it in my project. and it is not working anymore, please help
