### ISSUE TITLE
support additional generic for typing incoming body & query

### ISSUE THREAD

**Issue by danielroe** [unjs/h3#129]
would support something like this:

```js
export default defineEventHandler<{ result: string }, { foo: string }>(async event => {
  const { foo } = await useBody(event)
  return {
    result: foo
  }
})

const result = await $fetch('/api/test', {
  body: {
    // auto-completing body, requiring 
  }
})
```

**Follow-up tasks**
- [ ] add support for typing query/body in Nitro generated types & ohmyfetch (via options)

possibly could also consider params?

**Comment by kevinmarrec** [comment]
@danielroe Does `useQuery` & `useBody` already provides generic type ?

I also had schema validation Idea that could implement within the composables, like `useBody` handling bad requests using JSON schema type builder like https://github.com/sinclairzx81/typebox . `useBody` could then infer type from schema

**Comment by pi0** [comment]
Love the ideas!

`useBody` accepts type generic (`useParams` doesn't. PR welcome to add!)

We can introduce request validation with an external package like `h3-typebox` exposing `useValidatedBody(event)` with type inference and wrapping `useBody`. Later we might introduce a built-in util based on ajv/untyped or more h3 tailored DX.

I guess would be safer if we namespace second genetic for extensibility like `{ body: {}, query: {} }`. But how do you plan to type `useBody` call within `defineEventHandler` without explicitly giving generic to it @danielroe

**Comment by kevinmarrec** [comment]
Will be glad to help you guys on this stuff 🚀

**Comment by pi0** [comment]
Feel free to initiate h3-typebox @kevinmarrec ❤️ You can use unjs/template for starter.

**Comment by wobsoriano** [comment]
Now this is awesome!

**Comment by kevinmarrec** [comment]
I just released https://github.com/kevinmarrec/h3-typebox.

Feedbacks are welcome !

**Comment by pi0** [comment]
I just forgot this issue. @kevinmarrec Do you mind to open a PR to add your nice package to the readme?

**Comment by Atinux** [comment]
I would personnaly rename it to `h3-validator` and support the new `event` object @kevinmarrec 😊 

Awesome work so far ❤️

**Comment by kevinmarrec** [comment]
@pi0 I opened the PR :)

**Comment by pi0** [comment]
> I would personnaly rename it to h3-validator (but fine with h3-typebox if listed in Readme as validator options) and support the new event object @kevinmarrec 😊

This issue is still open for a built-in validation. Conventionally, by using the integration name in `h3-[integration]` we can support other possible validators from community.

**Comment by septatrix** [comment]
> But how do you plan to type `useBody` call within `defineEventHandler` without explicitly giving generic to it @danielroe

It might be possible by passing down the annotations to the event parameter which could then allow `readBody` to infer it from there.

**Comment by aspitrine** [comment]
Hi,

I see this issue as close but the $fetch typed part was not working (in nuxt) and i can't find any issue in the nuxt repository about this.

In the h3 repo it's ok, we have the generic and readBody was working.

What's the actual state for this ?

Thank's for all your hard work 🙏🏻

**Comment by septatrix** [comment]
In the PR closing this it is explicitly stated that using this for `$fetch` within nuxt is something which still has to be done. It is likely best if you create a new issue in the nuxt repository for tracking that.
