### ISSUE TITLE
Support `ReadableStream` responses (cloudflare)

### ISSUE THREAD

**Issue by Achrou** [unjs/h3#144]
In Cloudflare Workers , ReadableStream does not have `pipe` and `on` functions; resulting in a response type of `json`

https://github.com/unjs/h3/blob/f09ce91911cf5657a66a3a69a88a512c931d2be0/src/utils/response.ts#L47

For more information about Cloudflare Workers ReadableStream, please see:https://developers.cloudflare.com/workers/runtime-apis/streams/readablestream/#methods

**Comment by altryne** [comment]
Could this be why I'm not able to use readBody via cloudflare workers but can via npm run? 
https://github.com/nuxt-modules/supabase/issues/133#issuecomment-1361868398

**Comment by altryne** [comment]
I think his broke useBody in cloudflare workers @danielroe since the update

**Comment by altryne** [comment]
For what it's worth, this still breaks for me. 
One example is, auto generate routes like the one I just installed with nuxt/turnstile. 

For anyone arriving here before this is fixed (I would love to send a PR, just not sure where) here's my workaround: 

https://gist.github.com/altryne/54747e1a7b6d4adecc490f60dd0f636a

**Comment by altryne** [comment]
I think this is now closed here: 
https://github.com/unjs/h3/issues/363

**Comment by pi0** [comment]
Support for readable stream responses added via #457. Please check readme about nightly channel how to try this.
