### ISSUE TITLE
Add helper function for headers

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/h3#147]
Since its quite common to read the header strings, it would be nice if h3 could provide a helper function for this, which parses the headers and provides a structured way to access various common headers. For example, inspired by https://hapi.dev/module/accept/api/?v=5.0.2#parseallheaders one could have
```ts
parseHeaders(event).accept.mediaTypes
//  ["text/plain", "text/html", "application/json", "*/*"]
```

**Comment by NozomuIkuta** [comment]
@tobiasdiez @pi0 

If you have not yet started working on this feature, I can submit a PR. How?

---

By the way, I'm imagining composables like below so that H3 methods can be aligned:

```typescript
// Request phase
const headers = useHeaders(event) // all keys are lower-cased as 
const value = useHeader(event, name) // `name` is case-insensitive as `req.getHeader(name)`
headers[name.toLowerCase()] === value // true
const body = useBody(event)

// Response phase
appendHeader(event, name, value)
send(event, data, type)
sendStream(event, data)
```

We might want to make `useHeaders` and `useHeader` available in response phase (e.g. on `req`) as well, by either making them kinda generic or providing dedicated composables like `useReqHeader(s)` and `useResHeader(s)` for easy typing.

**Comment by NozomuIkuta** [comment]
It seems that `useBody` has been deprecated in the code base.

https://github.com/unjs/h3/blob/56bfe0ae7eea72051f6aa2ac838e3c947d365329/src/utils/body.ts#L75-L76

So, `readHeader(s)` or `parseHeader(s)` would be more suitable.

**Comment by pi0** [comment]
Sure thing @NozomuIkuta. I think we can introduce `getHeaders(event)`, `getHeader(event, name)` and `setHeader(event, name, value)` and maybe `appendHeader(event, name, value)` utils.

**Comment by tobiasdiez** [comment]
Thanks @NozomuIkuta! These helper methods are good to have.

Strictly speaking, my proposal/idea went a bit further and included a structured access to the headers, i.e. parse them:
```ts
// Instead of
getHeader(event, "Content-Type")
// returns string: text/html; charset=UTF-8

// One has
getHeader(event, "Content-Type")
// returns object: {mediaTypes: ["text/html"], charsets: ["UTF-8"]}
```

Don't you think it makes sense and be helpful for devs to have this structured access?
