### ISSUE TITLE
req.context not available for app.use()

### ISSUE THREAD

**Issue by renhiyama** [unjs/h3#149]
This code works:
```js
const router = createRouter()
 .get('/', () => 'Hello World!')
 .get('/hello/:name', req => `Hello ${req.context.params.name}!`)

app.use(router)
```

But this wont:
```js
app.use("/",(req,res)=>  `Hello ${req.context.params.name}!`)
```

And `app.get` doesnt even exist like expressjs has...
I dont want to create a new router, but straight away use app.use if possible. Thanks.

**Comment by pi0** [comment]
Hi dear @renhiyama. You should use `eventHandler` wrapper to create new handlers. Legacy `(req, res)` is going to be unsupported soon.

```js
import { eventHandler } from 'h3'
app.use("/", eventHandler((event)=>  `Hello ${event.context.params.name}!`))
```

Also @NozomuIkuta made a some new utils to access params. Check #158.
