### ISSUE TITLE
[Question] How to set status code 204?

### ISSUE THREAD

**Issue by maicWorkGithub** [unjs/h3#152]

**Comment by danielroe** [comment]
```js
export default defineEventHandler((event) => {
  event.res.statusCode = 204
  event.res.end()
})
```

**Comment by maicWorkGithub** [comment]
Thanks. Another question: what's the recommend way to write server background task, not triggered by client request kind? Should not be in `server` or `middleware` folder, should be `plugin` folder?

**Comment by maicWorkGithub** [comment]
Got it.
 Place it in any other folder, and import it in `nuxt.config.ts`, as `nitro` -> `plugin`. Is this right?

**Comment by pi0** [comment]
@danielroe Would you like to make a PR for null support with 204?

@maicWorkGithub Yes, you can use nitro plugins by creating `nitro/server/plugins/task.ts`. Only make sure task won't keep an open heandler in development mode.
