### ISSUE TITLE
IntelliSense error in H3Event

### ISSUE THREAD

**Issue by eduardosada** [unjs/h3#169]
### Environment

"nitropack": "0.4.24"

### Reproduction

https://stackblitz.com/edit/github-xukg4p-mpwena?file=routes%2Findex.ts,package.json

### Describe the bug

```ts
export default defineEventHandler((event) => {
  event.res.statusCode = 204;
  event.res.end();
});
```

IntelliSense error:
```
Property 'statusCode' does not exist on type 'ServerResponse'.(2339)
```

Seems like the error is in:

```ts
// node_modules/h3/dist/index.d.ts:1
import http, { OutgoingMessage } from 'http';
```

should be this:

```ts
import * as http from 'http';
import { OutgoingMessage } from 'http';
```

**Comment by pi0** [comment]
Intrestingly i can see the issue in stackblitz and not locally. Node.js listener signature is also `req: IncommingMessage, res: ServerResponse`...

**Comment by pi0** [comment]
And interestingly only reproducible on external package usage https://stackblitz.com/edit/github-xukg4p-ktgc4m?file=package.json,index.ts

**Comment by eduardosada** [comment]
> Found a fix:
> 
> ```
> pnpm i @types/node
> ```

Sorry, I thought that would fix it but I was wrong :(

**Comment by pi0** [comment]
Updated stackblitz with latest h3 and types/node still not working... Any ideas @danielroe ?

**Comment by NozomuIkuta** [comment]
One possible solution is to enable `esModuleInterop`.
For example, on developer's side:

```json5
// tsconfig.json
{
  "extends": "./.nitro/types/tsconfig.json",
  "compilerOptions": {
    "esModuleInterop": true
  }
}
```

Refs:

- https://www.typescriptlang.org/tsconfig#esModuleInterop
- https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop
