### ISSUE TITLE
Type of return value of get header(s) utils is wrong

### ISSUE THREAD

**Issue by NozomuIkuta** [unjs/h3#176]
For example, `getRequestHeader` returns `string | string[]` while it should return `string | string[] | undefined`, because HTTP headers might be not sent from the client.

To be honest, I added these kinds of utilities to h3, so I will fix them. 🙏 
I will check other related utilities as well.

Related issue: https://github.com/NozomuIkuta/h3-cors/issues/1

**Comment by NozomuIkuta** [comment]
I found that type of return value of get header(s) utils is correct on h3 side.
Note that its return type is `string | string[] | undefined` as expected and as defined in `http.d.ts`.

<img width="1516" alt="Screen Shot 2022-09-13 at 23 34 11" src="https://user-images.githubusercontent.com/16436160/189929832-0e898511-47f1-4780-8643-8f8d64f07fb6.png">

On the other hand, its return type is `string | string[]` in my h3-cors code base.

<img width="1030" alt="Screen Shot 2022-09-13 at 23 34 43" src="https://user-images.githubusercontent.com/16436160/189929854-f0345f10-cdde-4a1a-a16f-a55d87ccf9f0.png">

The difference between these 2 code bases is whether `strict: true` is set in `tsconfig.json` or not.
With `strict` set true, `string | string[] | undefined` is suggested in h3-cors as in h3.

<img width="1530" alt="Screen Shot 2022-09-13 at 23 38 44" src="https://user-images.githubusercontent.com/16436160/189930631-5ca8dc41-7d5e-4eaf-9b90-84ce52bd0a20.png">

---

I used [unjs/template](https://github.com/unjs/template) for scaffolding of h3-cors. So, for compatibility and consistency in terms of type safety and developer experience, `strict: true` should be added to the template.

@pi0 @danielroe 
What do you think?

**Comment by danielroe** [comment]
I would agree that `strict: true` should be the default. @pi0?

**Comment by pi0** [comment]
Nice idea for enabling strict :)
