### ISSUE TITLE
How to handle FormData?

### ISSUE THREAD

**Issue by lvzhenbo** [unjs/h3#199]
I have a situation where I am uploading some string data to the server along with a file, here is an example
```javascript
// nuxt
const params = new FormData();
params.append('converter', epubFormValue.value.converter);
params.append('file', epubFormValue.value.fileList[0].file);
const res = await useFetch('/api/epub', {
  method: 'POST',
  body: params,
});

// h3
export default defineEventHandler(async (event) => {
  const body = await useBody(event);
  return {
    converter: body,
  };
});
```
I found that I can't get the string data and the file separately, how can I do that?

**Comment by lvzhenbo** [comment]
Can someone solve my problem, I switched from express to nuxt, express can process formdata very conveniently, but I can't even find an example for h3

**Comment by andrewa813** [comment]
I used [formidable](https://www.npmjs.com/package/formidable) for this. I don't think it's supported yet on h3.

    const form = new formidable.IncomingForm()
    const {fields: body, files} = await new Promise((resolve, reject) => {
      form.parse(req, (err, fields, files) => {
        if (err) reject(err)
        resolve({fields, files})
      })
    })

**Comment by wobsoriano** [comment]
https://github.com/unjs/h3/issues/43#issuecomment-1069225214

```ts
import type { H3Event } from 'h3'
import formidable from 'formidable'

export function readFiles(event: H3Event, options?: formidable.Options): Promise<formidable.Files> {
  return new Promise((resolve, reject) => {
    const form = formidable(options)

    form.parse(event.req, (err, _fields, files) => {
      if (err)
        reject(err)

      resolve(files)
    })
  })
}
```

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/h3-formidable

**Comment by lvzhenbo** [comment]
Thanks a lot, solved it, but I think it would be nice if h3 could automatically handle formdata

**Comment by descovi** [comment]
An easier solution is to use readFormData(event) - https://h3.unjs.io/utils/request#readformdataevent
