### ISSUE TITLE
How to augment event.req type?

### ISSUE THREAD

**Issue by manniL** [unjs/h3#209]
Hey! After upgrading to 0.8.x, I wonder how to augment `event.req`. This is important when e.g. using express/connect middleware (looking at you https://github.com/unjs/ezpass) which is heavily relying on it.

**Comment by pi0** [comment]
Hi. I believe express at least has an extended interface for its handlers passing to `express().use(...)` that can be augmented. For h3 we are reducing `req`/`res` dependency even more. Allowing extending `req` type is kinda counter attempt... As for ezpass we shall do the same and rely in `Event` augmentation instead. (I've to close this one as not planned but will keep looking for ezpass migration)

**Comment by manniL** [comment]
Thanks for the detailed info!
But what to do if we use legacy express middleware that "will" augment req/res? 🤔

**Comment by richardeschloss** [comment]
Also, how will one be able to re-use error middleware? Will `Event` have `error` attached to it? Or will it be inferred from what's on `res` ? 

In express, it may be common for a lot of middleware to use the following [function signature](https://expressjs.com/en/guide/error-handling.html#the-default-error-handler):
```js
function errorHandler (err, req, res, next) { // 4 arguments instead of the typical 3
  if (res.headersSent) {
    return next(err)
  }
  res.status(500)
  res.render('error', { error: err })
}
```

The above handler will be hit only if previous middleware called `next` with a non-null argument. How will h3 handle such an error?

**Comment by taksugit** [comment]
In my case, I handle it by extension of `onError` when I want `err`

```ts
export default defineEventHandler((event) => {
  const nitroApp = useNitroApp()
  const errorHandler = nitroApp.h3App.options.onError
  nitroApp.h3App.options.onError = (err, event) => {
    if (errorHandler) {
      errorHandler(err, event)
    }
    // something
  }
})
```
