### ISSUE TITLE
Unable to read body of PUT request

### ISSUE THREAD

**Issue by joshvr27** [unjs/h3#211]
How can I read the body of a put request?

I am using middleware in nuxt3, this middleware needs to read the body of a PUT request

currently I am trying to use 
`readBody(event)`
but it says this method is only allowed for POST requests.

Surely this is wrong because PUT requests should allow for a request body?

or is there another way to get this data?

**Comment by danielroe** [comment]
Would you provide a reproduction? `h3` allows for reading body on `PUT` requests:

https://github.com/unjs/h3/blob/ba2fe08c1ebd0f9aa5c5e4533d0f58fbd8cead79/src/utils/body.ts#L9
