### ISSUE TITLE
Generated d.ts causes Type Error

### ISSUE THREAD

**Issue by mei23** [unjs/h3#216]
I am using h3 from TypeScript.
But I get a Type Error.

The generated d.ts references `src/types`.
But src/types doesn't exist.
![image](https://user-images.githubusercontent.com/30769358/198815533-b6ea5773-9773-428e-96bc-a64b4bc19ff6.png)

![image](https://user-images.githubusercontent.com/30769358/198815530-f75d0bcc-c5b0-4b32-a136-b3b450cb29a5.png)

**Comment by nmathew98** [comment]
Hi can I be assigned to this?
