### ISSUE TITLE
question. How `setImmediate` improve performance?

### ISSUE THREAD

**Issue by ChangJoo-Park** [unjs/h3#23]
Hello @pi0 . I can not find for place to question. So I leave my question here.

I saw yesterday your [commit](https://github.com/unjs/h3/commit/524ed1f4665e93f517f59dd45620c4b107b229ed#diff-d1b81492ea5c1893cd4f7c95a446b316afe4ea2df9f8b1bd2b19447ba27f3b10R8
). I understood early return (break to return) is nice pattern in the upper diff `src/app.ts`.
but, I didn't understand to use `setImmediate`. All of request already asynchronous. Why need `Promise` with `setImmediate` ?

I tried to benchmark  before / after `setImmediate` . I got almost same result.

**Comment by pi0** [comment]
Hi @ChangJoo-Park. Nice that you checked :) To be honest I've not clear idea why. But you can try `yarn profile` script to see flame-graph (`yarn build` is required on a change). It seems event loop gets blocked for sending response without `setImmediate`. And BTW I've inspired deferring send from [connect](https://github.com/senchalabs/connect/blob/52cf21b211272519caeef3bb5064c3430f4feb43/index.js#L151).

**Comment by ChangJoo-Park** [comment]
Thank you for reply! I retry with `yarn profile` Please see result below.
I use Node.js 14 on WSL. 0x cannot launch browser with 0x 😭  I'll fix script and rerun for my env.

![image](https://user-images.githubusercontent.com/1451365/113228493-f7e81600-92cf-11eb-8a76-e6ff9d2cf3ef.png)

![image](https://user-images.githubusercontent.com/1451365/113228528-07fff580-92d0-11eb-834e-1c54bfe8d7aa.png)

> I tried to benchmark before / after setImmediate . I got almost same result.

Before I try I saw only throughput. It slightly same.

### weird result express with setImmediate

h3's the way of return response is just return something, It is not same with express. 

So. I try express with this code.  always 'just res.send' faster than with setImmediate.

```js
app.get('/', (req, res) => {
  return res.send({ hello: 'world' })
})
```

![image](https://user-images.githubusercontent.com/1451365/113229701-7776e480-92d2-11eb-85a6-818940609625.png)


```js
app.get('/', (req, res) => {
  setImmediate(() => res.send({ hello: 'world' }))
})
```
![image](https://user-images.githubusercontent.com/1451365/113229730-8198e300-92d2-11eb-8a29-f5bf1615897d.png)

**Comment by ChangJoo-Park** [comment]
h3 use promise with setImmediate for nitro at this time. I understood this issue.
