### ISSUE TITLE
How to use within Nuxt v3 as server middleware

### ISSUE THREAD

**Issue by chrisnoden** [unjs/h3#234]
If I wanted to use your example:

```
import { createApp, eventHandler, createRouter } from 'h3'

const app = createApp()

const router = createRouter()
 .get('/', eventHandler(() => 'Hello World!'))
 .get('/hello/:name', eventHandler(event => `Hello ${event.context.params.name}!`))

app.use(router)
```

within Nuxt v3 (rc 14 or release version) to handle all requests to `/api/**` (eg `/api/hello/chris`)

How would I do this?

**Comment by NozomuIkuta** [comment]
@chrisnoden 

I'm not 100% sure what you are looking for, but you might want to check [the corresponding part of Nuxt doc](https://nuxt.com/docs/guide/directory-structure/server), where how you can integrate h3 with Nuxt 3.

If you want to let an event handler handle all the routes, then "catch-all route" ([ref](https://nuxt.com/docs/guide/directory-structure/server#catch-all-route)) would be what you are looking for.

**Comment by chrisnoden** [comment]
> @chrisnoden
> 
> I'm not 100% sure what you are looking for, but you might want to check [the corresponding part of Nuxt doc](https://nuxt.com/docs/guide/directory-structure/server), where you can find ways to integrate h3 with Nuxt 3.
> 
> If you want to let an event handler handle all the routes, then "catch-all route" ([ref](https://nuxt.com/docs/guide/directory-structure/server#catch-all-route)) would be what you are looking for.

Thanks. That doc is for Nuxt v2. I have followed the Nuxt v3 docs also for the equivalent and am unable to get any permutation I have tried to work. I used to be able to get it to work using a `serverMiddleware` hook in the nuxt config - but that has been removed in a recent RC. I have also tried `/server/api/[...].ts` as the middleware file with the above code block. No joy.

Since h3 is developed by similar core team members I assume they have a plan for how to leverage h3 within Nuxt v3.

**Comment by wobsoriano** [comment]
A nitro plugin fixes this

```ts
import { eventHandler, createRouter } from 'h3'

const router = createRouter()
 .get('/hello', eventHandler(() => 'Hello World!'))
 .get('/hello/:name', eventHandler(event => `Hello ${event.context.params.name}!`))

export default defineNitroPlugin((nitro) => {
  nitro.h3App.stack.unshift({
    route: '/api',
    handler: router.handler
  })
})
```

```ts
export default defineNuxtConfig({
  nitro: {
    plugins: ['~/nitro/your-plugin']
  },
})
```

**Comment by marr** [comment]
This probably should have been answered by someone sooner, but better late than never right?!

https://stackblitz.com/edit/github-zdqehg?file=nuxt.config.ts,app.vue,server%2Frouter.ts

There is some caveats that I wasn't sure how to get around. Mostly that the prefix is not optional within the router definition. Ie, in your `serverHandler` config defined in nuxt.config.ts, you specify `route` like `/api/**`. In the handler,
you must also specify the root: `router.get('/api/foo', ...)`.

Seems a bit finicky, but ultimately doable.

**Comment by Barbapapazes** [comment]
> If I wanted to use your example:
> 
> ```
> import { createApp, eventHandler, createRouter } from 'h3'
> 
> const app = createApp()
> 
> const router = createRouter()
>  .get('/', eventHandler(() => 'Hello World!'))
>  .get('/hello/:name', eventHandler(event => `Hello ${event.context.params.name}!`))
> 
> app.use(router)
> ```
> 
> within Nuxt v3 (rc 14 or release version) to handle all requests to `/api/**` (eg `/api/hello/chris`)
> 
> How would I do this?

Hello ! 

In Nuxt3, you have Nitro, https://nitro.unjs.io. Nitro is a powerful server framework on top of h3.

**Comment by Hebilicious** [comment]
Thanks @marr and @Barbapapazes, closing this.
