### ISSUE TITLE
eventHandler vs defineEventHandler

### ISSUE THREAD

**Issue by P4sca1** [unjs/h3#237]
Is it supposed to have both of them (eventHandler being an alias for defineEventHandler), or was one supposed to be removed with 1.0?

**Comment by nopeless** [comment]
@P4sca1 they are the exact same thing. I think we should deprecate defineEventHandler

**Comment by ENBYSS** [comment]
@nopeless personally I'd rather `eventHandler` be deprecated, since `defineEventHandler` is clearer and being used as the defacto way of defining APIs in Nuxt3

**Comment by pi0** [comment]
Yes they are aliases and we kept `defineEventHandler` specifically for consistency in nuxt. While in general usage it is shorter and easier to use `eventHandler`.

**Comment by nopeless** [comment]
> @nopeless personally I'd rather `eventHandler` be deprecated, since `defineEventHandler` is clearer and being used as the defacto way of defining APIs in Nuxt3

Its longer. It would be clearer for people using JS files but if you are using ts, eventHandler is fine
