### ISSUE TITLE
`res._implicitHeader` is not a function with `express-session`

### ISSUE THREAD

**Issue by nopeless** [unjs/h3#239]
```ts
// Middleware definition
fromNodeMiddleware(
    session({
      secret,
      resave: false,
      saveUninitialized: true,
    }) as any
  )

// Used in nuxt eventually
export default defineEventHandler(middleware);
```

I belive this is a minor error from either `session`'s part or `h3` not supporting compatibility

If the issue isn't seem obvious enough, let me know so I can give a more detailed report and a reproduction

**Comment by NozomuIkuta** [comment]
@nopeless 

> error from either session's part or h3 not supporting compatibility

> I can give a more detailed report and a reproduction

TBH, it's the best way to provide a reproduction from the beginning, for other people to find where is the root cause and consequently help you in some way.

**Comment by nopeless** [comment]
Sometimes the issue is very obvious; I guess this isn't the case

**Comment by nopeless** [comment]
https://stackblitz.com/edit/nuxt-starter-ybzyms?file=app.vue,pages%2Findex.vue,server%2Fmiddleware%2Fsession.ts

Here is a reproduction

Once the server is running, copy the link and paste it in your browser

**Comment by pi0** [comment]
`express-session` requires `express` app polyfills to work. Something like this partially works:

```ts
import express from 'express';
import session from 'express-session';

export default fromNodeMiddleware(express().use(session({
  secret: '123',
  resave: false,
  saveUninitialized: true,
}) as any))
```

I would suggest you to use iron-session or another package that is not depending on express. Iron session example: https://stackblitz.com/edit/github-z5kpi7?file=app.vue (try locally)

(note: stackblitz does not supports setting cookies. try both locally)

**Comment by pi0** [comment]
There is also https://github.com/wobsoriano/h3-session but i haven't tried it nor endorse.

**Comment by nopeless** [comment]
Ah so h3 is not fully compatible with express (or express session is using a non-api)

Anyway, thanks for clarifying

**Comment by nopeless** [comment]
@pi0 I came back to this issue because I encountered another similar issue with another express plugin. I feel like this is worth mentioning somewhere in the docs

**Comment by pi0** [comment]
Mentioning in docs seems a really good idea @nopeless would you mind to draft a PR?

**Comment by nopeless** [comment]
> Mentioning in docs seems a really good idea @nopeless would you mind to draft a PR?

Let me take some time to read source. I'll make a pr soon

**Comment by nopeless** [comment]
#253 Will be the new tracker for this
