### ISSUE TITLE
Body parser/form parser/url encoded parser by default

### ISSUE THREAD

**Issue by nopeless** [unjs/h3#259]
### Describe the feature

Every time I have to include some kind of form parsing it increases the development time by hours. Each time I have to find npm and find a package that works. It would be nice to have this parsed by default and exposed somewhere as a getter so developers don't have to worry about anything

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by NozomuIkuta** [comment]
@pi0 

FYI, [Hono](https://honojs.dev/) takes this approach (exporting a lot of default middlewares from main repository), which I agree is good DX.

**Comment by nopeless** [comment]
> @pi0 
> 
> FYI, [Hono](https://honojs.dev/) takes this approach (exporting a lot of default middlewares from main repository), which I agree is good DX.

Thanks for responding @NozomuIkuta , take a look at this issue https://github.com/nuxt/framework/issues/9465#issue-1472265024

**Comment by Hebilicious** [comment]
We should probably document this or expose a similar helper,
But something that you can do without any dependencies in recent version of node.js is  this :

```ts
// H3
export async function getRequestFromEvent(event: H3Event) {
  const url = new URL(getRequestURL(event))
  const method = getMethod(event)
  const body = method === "POST" ? await readRawBody(event) : undefined
  return new Request(url, { headers: getRequestHeaders(event) as any, method, body })
}

// H3
export async function getFormData(event: H3Event) {
  return (await getRequestFromEvent(event)).formData()
}
```

**Comment by pi0** [comment]
The new `readFormData` utility is available via https://github.com/unjs/h3/pull/421. You can early test it via nightly channel (check reademe for how)
