### ISSUE TITLE
Better docs / particularly on returning an image response

### ISSUE THREAD

**Issue by platform-kit** [unjs/h3#265]
### Describe the feature

Hi, this is a general request for a real docs website, ala the ones for Nitro https://nitro.unjs.io/  - with searchable examples of common use cases.

Which brings me to the example in question I would love to see (and would love to see the answer in this thread as well, for my immediate use): how the heck do you return an image?

Say I have an image encoded as a base64 dataUrl string, how am I meant to return it in h3, so that the route in question shows an image in the browser, rather than a string or JSON?

Thanks in advance.

PS - As someone coming to this project from Nuxt (15 years full stack development, most of my Node work in express/koa), I find the DX here extremely frustrating.

**Comment by cuebit** [comment]
@platform-kit can't have you be left hanging for 2 weeks lad 😆 

Something on the lines of:

```js
eventHandler((event) => {
  const encodedStr = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkqAcAAIUAgUW0RjgAAAAASUVORK5CYII='
  const image = Buffer.from(encodedStr, 'base64')
  event.node.res.setHeader('content-type', 'image/png')
  event.node.res.setHeader('content-length', image.length)
  return image
})
```

**Comment by pi0** [comment]
Sorry for frustrations. We should indeed improve documentation of h3 utilities and also in Nitro, more common practices. @cuebit explained well how to convert a base64 string into Buffer as response. H3 simply accepts any response to be returned.
