### ISSUE TITLE
How to get request IP address?

### ISSUE THREAD

**Issue by cawa-93** [unjs/h3#272]
### Describe the feature

For our business logic, we need to receive information about the IP address of the requester. I did not find relevant information in your documentation

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by NozomuIkuta** [comment]
@cawa-93 

IP address is handled at lower layer than h3.

You could find information by googling Node.js `http.ClientRequest` or its `socket` property (i.e. `net.Socket` class).

By the way, IP address that you need might be value of HTTP header, which depends on your infra architecture (e.g. using proxy server).

**Comment by cawa-93** [comment]
Tiny note

>  In terms of h3, you can access it via `event.req.*` property.

`event.req` is deprecated at the moment. You should use `event.node.req` instead
