### ISSUE TITLE
not all values present when using `readBody` with `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by danielroe** [unjs/h3#275]
I dont think [this solution](https://github.com/unjs/h3/blob/ac5432f38c7902c107c048b2f8c9f767a567c1c1/src/utils/body.ts#L67) works properly for all use cases. With URLSearchParams, it's possible to have multiple values for the same key, but with objects, you would overwrite the data. This would cause data loss. Also, the values in URLSearchParams will always return strings, which isn't the case for Objects.

For example:

```js
const d = new URLSearchParams([['a', 1],['a', 2]])
const o = Object.fromEntries(d.entries())

console.log(d.getAll('a')) // returns ['1', '2']
console.log(o['a']) // returns 2
```

The best solution I've found is to use the "[qs](https://www.npmjs.com/package/qs)" package:

```js
if (headers['content-type']?.includes('application/x-www-form-urlencoded')) {
  body = qs.parse(body);
}
```

_Originally posted by @AustinGil in https://github.com/unjs/h3/issues/40#issuecomment-1346311614_

**Comment by alphaelf** [comment]
as i reported in [#278](https://github.com/unjs/h3/pull/278#issuecomment-1494084676) you need add `destr` to convert body values before return it
i have an issue in `nuxt-auth` module when i use `signIn` method with `redirect:false` and `callbackUrl: undefined` option, these options get receives as `string` in `readBody` but these must be `boolean` and `undefined` type
