### ISSUE TITLE
sort stack

### ISSUE THREAD

**Issue by pi0** [unjs/h3#3]
automatically sort by layer.route.length to avoid ordering issues (with an AppOption to disable) 

Alternative: sort(app) | app.sort()

**Comment by danielroe** [comment]
Could I suggest also passing in an option `{ priority: number }` - as typically you want the longest *route handler* first but the shortest *middleware* first...

**Comment by pi0** [comment]
More thinking, sorting is the job of a router, and supporting it breaks the middleware ordering concept.
