### ISSUE TITLE
feat: add an utility function to get protocol

### ISSUE THREAD

**Issue by NozomuIkuta** [unjs/h3#306]
### Describe the feature

h3 has some kinds of utility functions to get information about the request (e.g. `getMethod()`).

It would be also good to have that utility function(s) to get protocol of the request. Currently, we have to install another unjs package, [`is-https`](https://github.com/unjs/is-https) package, to detect HTTPS, or implement similar logic by ourselves.

So, exporting such functionality, like `getProtocol` or `isHTTPS`, from h3 would be beneficial for developers in terms of DX.

cf. built-in CORS support (#82) vs. [my CORS package](https://github.com/NozomuIkuta/h3-cors)

---

More generally, we might want to create an issue where we can discuss what kind of middlewares and utility functions should be exported from h3, rather than providing them as 3rd-party package.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by ashutosh887** [comment]
I would like to work on this @NozomuIkuta

**Comment by NozomuIkuta** [comment]
@ashutosh887 

Please feel free to submit a PR 👍

**Comment by ashutosh887** [comment]
Sure @NozomuIkuta . Please assign me

**Comment by NozomuIkuta** [comment]
@ashutosh887 

I guess we don't use `asignees` section in this repository.
Since you said you would work on this issue, no one would take over unless you hand it over.

**Comment by ashutosh887** [comment]
How would you like the function to be?
I'm trying to set it up.
Also, I would like to propose an Idea to create a **Contributing.md** for new comers/contributers to get started and get a general Idea.

**Comment by NozomuIkuta** [comment]
IMHO, migrating `is-https` codebase to h3 is an option, like we did for CORS support. For naming, `isXYZ` would be nice for consistency, because we already have `isPreflightRequest` and `isCorsOriginAllowed`.

Other related functions (e.g. `getProtocol`) could utilize `ufo` package under the hood.

You might want to submit a PR anyway based on your ideas and start a discussion in PR thread.

Whichever, @pi0 have the right to determine the final spec as the author of h3 (according to [unjs governance policy](https://github.com/unjs/governance)).

---

As for contribution, here are summary for you at the moment:

- Use Node.js LTS version
- Use `pnpm` by enabling corepack (version is specified in `package.json` so you don't have to worry about it)
- You should define utility function(s) in an appropriate place in `src/utils` directory (either of existing file(s), or new file(s))
- Make sure to add unit test in an appropriate place in `test` directory (otherwise, they wouldn't merge your PR)
- Make sure to add explanation about the new utility function(s) to Utilities section of README
- It's recommended to add JSDoc comments to the new function(s), so that developers can see API on their editors without googling (if you are not familiar with it, you can ask for help in the PR)

By the way,  at the moment, Development section of [unjs/template](https://github.com/unjs/template#development) would correspond to `CONTRIBUTING.md` (chronologically, h3 doesn't have such a section). But, I agree that it's worth adding more information to Development section, so that more and more people like you can contribute with confidence.

You are also welcomed to submit a PR to enhance h3 README, and to [unjs/template](https://github.com/unjs/template) for future unjs packages.
