### ISSUE TITLE
[h3] [unhandled] next is not a function at Object.serveStatic [as handler]

### ISSUE THREAD

**Issue by wesley3295** [unjs/h3#312]
### Environment

Node: v16.19.0
OS: Windows
`{
  "name": "project",
  "version": "1.0.0",
  "private": true,
  "scripts": {
  ...
  },
  "dependencies": {
    "@koumoul/vjsf": "^2.21.0",
    "@nuxtjs/auth-next": "^5.0.0-1617968180.f699074",
    "@nuxtjs/axios": "^5.13.6",
    "@vueuse/core": "^9.12.0",
    "axios-retry": "^3.1.9",
    "core-js": "^3.27.2 ",
    "defu": "^6.1.2",
    "dotenv": "^16.0.3",
    "jsonwebtoken": "^9.0.0",
    "ldap-authentication": "^2.3.2",
    "lodash-es": "^4.17.21",
    "marklogic": "^2.9.1",
    "multer": "^1.4.5-lts.1",
    "nanoid": "^4.0.0",
    "nuxt-edge": "latest",
    "parse-duration": "^1.0.2",
    "typescript": "^4.9.5",
    "vue-toastification": "1.7.11",
    "vuedraggable": "^2.24.3",
    "zingchart": "^2.9.10",
    "zingchart-vue": "^2.0.4"
  },
  "devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27909973.a4c5d19",
    "@nuxtjs/pwa": "^3.3.5",
    "@nuxtjs/vuetify": "^1.12.1",
    "@vitest/ui": "^0.28.3",
    "@vue/test-utils": "^2.2.8",
    "@vueuse/nuxt": "^9.12.0",
    "babel-core": "7.0.0-bridge.0",
    "c8": "^7.12.0",
    "deepmerge": "^4.3.0",
    "eslint-config-prettier": "^8.6.0",
    "prettier": "^2.8.3",
    "sass": "^1.47.0",
    "sass-loader": "^10.1.1",
    "std-env": "^3.3.1",
    "supertest": "^6.3.3",
    "vitest": "^0.28.3",
    "webpack": "^4.46.0"
  }
}
`

### Reproduction

Cannot reproduce at this time

### Describe the bug

H3 not compatible with latest version of nuxt/bridge or serveStatic module.

### Logs

```sh
Nuxi 3.0.0                                                                                                                                      14:12:41
Nuxt 2.16.0-27720022.54e852f with Nitro 1.0.0                                                                                                   14:12:41
debug mode: undefined                                                                                                                           14:12:44
                                                                                                                                                14:12:44
  > Local:    http://localhost:3000/
  > Network:  http://10.244.0.68:3000/
  > Network:  http://192.168.1.19:3000/
  > Network:  http://192.168.191.51:3000/
  > Network:  http://[fca0:f9af:79a0:4b93:cf7f::1]:3000/


 WARN  [h3] Implicit event handler conversion is deprecated. Use eventHandler() or fromNodeMiddleware() to define event handlers.               14:12:45
     Route: /_nuxt/
     Handler: function serveStatic (req, res, next) {
    if (req.method !== 'GET' && req.method !== 'HEAD') {
                                                                                                                                                14:14:31  
✔ Client
  Compiled successfully in 1.73m
√ Nitro built in 6743 ms                                                                                                                  nitro 14:14:39
i Waiting for file changes                                                                                                                      14:14:39

 ERROR  [h3] [unhandled] next is not a function                                                                                                 14:15:00

  at Object.serveStatic [as handler] (node_modules\serve-static\index.js:75:16)
  at Object.handler (/C:/projects/project/node_modules/h3/dist/index.mjs:840:31)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async toNodeHandle (/C:/projects/project/node_modules/nuxi/dist/chunks/index2.mjs:994:7)
```

**Comment by pi0** [comment]
Hi! Please open an issue in nuxt/nuxt with reproduction 🙏🏼
