### ISSUE TITLE
proxying multiple cookies and split by comma

### ISSUE THREAD

**Issue by meixger** [unjs/h3#318]
### Describe the feature

When proxying requests in Nuxt 3 with `proxyRequest()`, only a single combined set-cookie header with multiple comma separated cookies is returned.

```
// from upsttream
Set-Cookie: user=alice; Path=/; Expires=Thu, 01 Jun 2023 10:00:00 GMT; HttpOnly
Set-Cookie: role=guest; Path=/
```

```
// from unjs/h3
set-cookie: user=alice; Path=/; Expires=Thu, 01 Jun 2023 10:00:00 GMT; HttpOnly, role=guest; Path=/
```

```
// browser breaks on split
user=alice; Path=/; Expires=Thu
01 Jun 2023 10:00:00 GMT; HttpOnly
role=guest; Path=/
```

How is unjs/h3 supposed to handle multiple set-cookie headers when proxying from upstream back to browser?

cc @pi0: Would this https://github.com/meixger/h3/commit/7f2fd3be2c1b1c6296444bf52d7613f46fe12bb0 be the right approach or is it out of scope for h3?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. Thanks for explaining and providing implementation. Quickly reading it seems reasonable to be supported by proxy util 👍 Do you mind to open a PR?
