### ISSUE TITLE
`useSession` throws unsupported error in stackblitz 

### ISSUE THREAD

**Issue by angelhdzmultimedia** [unjs/h3#337]
### Environment

**Node:** 16.14.2
**IDE:** stackblitz.com
**pnpm:** 7.13.6
**nuxt:** 3.2.2
**h3:** 1.5.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-scbadp?file=server%2Fapi%2Fcount.get.ts

### Describe the bug

![image](https://user-images.githubusercontent.com/10191085/219824671-aa1906c4-0fed-4c4b-b7ac-700392eae131.png)

**Comment by angelhdzmultimedia** [comment]
### Update

I intended to post this in the nuxt repo. Got confused.
But yeah, they are related.

I tried using a server middleware using h3 directly with its own http server and host/port, to rule out any incompatibility of session with nuxt, but still got error:

![image](https://user-images.githubusercontent.com/10191085/219838231-0bb95387-a515-40e3-81af-1ab73cfe321c.png)

The server per se is receiving the request from the client (app.vue), and returning the value.
The error comes the moment I add session.

![image](https://user-images.githubusercontent.com/10191085/219838879-51a95dd9-c88d-416f-8688-6a6ab578ae2f.png)

**Comment by ashutosh887** [comment]
@angelhdzmultimedia I would like to work on it

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia I would like to work on it

Thank you! I hope you can find a solution.

**Comment by angelhdzmultimedia** [comment]
> @angelhdzmultimedia I would like to work on it

Not rushing. Just want to know the status, to know if I will wait for this to be solved, or explore `sidebase/nuxt-session`. Thank you!

**Comment by pi0** [comment]
Hi. This issue seems from stackblitz only not supporting some web crypto methods used to encrypt the session. If you run it locally, it works.

(small note, in `count.get.ts` line 10, you forgot an `await` for `session.update`)

Keeping this issue open until investigating more on stackblitz side.

**Comment by angelhdzmultimedia** [comment]
> Hi. This issue seems from stackblitz only not supporting some web crypto methods used to encrypt the session. If you run it locally, it works.
> 
> (small note, in `count.get.ts` line 10, you forgot an `await` for `session.update`)
> 
> Keeping this issue open until investigating more on stackblitz side.

Thank you very much! Have a nice rest of the day.

**Comment by pi0** [comment]
Hi. I have made some more investigations on this. Here is a more minimum h3 only and crpyto only reproduction: (use `node h3.mjs` and `node crypto.mjs`) to reproduce

https://stackblitz.com/edit/stackblitz-starters-coskra?description=Starter%20project%20for%20Node.js,%20a%20JavaScript%20runtime%20built%20on%20Chrome%27s%20V8%20JavaScript%20engine&file=crypto.mjs,h3.mjs&title=node.new%20Starter

**Comment by angelhdzmultimedia** [comment]
> Hi. I have made some more investigations on this. Here is a more minimum h3 only and crpyto only reproduction: (use `node h3.mjs` and `node crypto.mjs`) to reproduce
> 
> https://stackblitz.com/edit/stackblitz-starters-coskra
> 
> ~> Moving to upstream [brc-dd/iron-webcrypto#13](https://github.com/brc-dd/iron-webcrypto/issues/13)

Thanks a lot! Great job you've been doing. Highly appreciate it. Nice to see more good stuff being added to Nuxt.

**Comment by pi0** [comment]
Hi. Good news! Session examples are now supported officially on stackblitz 🥳

**Comment by angelhdzmultimedia** [comment]
> Hi. Good news! Session examples are now supported officially on stackblitz 🥳

Amazing job as always. Appreciate it a lot! Lots of health and peace. 💚🔥🤝
