### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by cfv1984** [unjs/h3#34]
Hi! Very interested on this. I can get express and the core http server to serve over HTTPS quite easily, but I... don't know enough about h3 to do that with your library? Is there documentation on the topic?

**Comment by pi0** [comment]
Hey! You can use [listhen](https://github.com/unjs/listhen) to quickly start an HTTPS server from h3, without even need of SSL creation ;)

**Comment by cfv1984** [comment]
Thanks!
