### ISSUE TITLE
expand api documentation 

### ISSUE THREAD

**Issue by BananaAcid** [unjs/h3#340]
### Describe the feature

Please describe what each function does and is meant to be used for (and ideally an example), in the api documentation.

1. As well as when context is filled / how long it is persistent.

2. useSession - data does not seem to be persistent, please add a note how this could be changed (a usage example)

... having to read the source files to get a clue on what a function does, because the documentation does not contain an explanation seems to me to be very cumbersome. 

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
We are working with @manniL to add more detailed docs both as guide and better API docs in jsdocs/readme.

**Comment by Barbapapazes** [comment]
related to #595

Hello @BananaAcid, do not hesitate to provide some feedbacks on the PR!
