### ISSUE TITLE
Get access to protocol, host and port of request

### ISSUE THREAD

**Issue by septatrix** [unjs/h3#345]
### Describe the feature

This is required to get a full, standards compliant `new URL()` which some libraries require without having to hardcode these values.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. If you want exact URL compliance, please consider the native `URL` itself. It is supported in most of modern runtimes today :)

**Comment by septatrix** [comment]
How can I access that? I haven't found anything in the document (of either h3 or nuxt)

**Comment by pi0** [comment]
This is out of this package's context. You can always construct URL yourself. BTW made https://github.com/unjs/h3/issues/347 i think this is what you meant?

**Comment by septatrix** [comment]
> This is out of this package's scope. You can always construct URL yourself.

This is also what I currently do though I have to hardcore host, port and protocol which I would like to avoid.

> BTW made #347 i think this is what you meant?

Yes, perfect :)
