### ISSUE TITLE
How to annotation query type?

### ISSUE THREAD

**Issue by maicss** [unjs/h3#349]
### Environment

node : 18.12.1
nuxt: 3.0.0
h3: 1.0.2

### Reproduction

export default defineEventHandler(async (event) => {
  const { res } = event.node
  const { code, name, someNumber } = getQuery(event)
})

### Describe the bug

`code`, `name`, `someNumber` types are infer to  `string | QueryValue[] | null`

How do I give types of them? Not where I use them with `as` assert.
like:
```
const handle Query = (code: string, name: string, index?: number) => {}
handleQuery (code as string, name as string, someNumber as number)
```

**Comment by oleghalin** [comment]
`getQuery` doesnt accept generic, so for now you can mark it as type using `as` construction 

```
const query = getQuery(event) as Query;
```

**Comment by maicss** [comment]
OK, fine.
Will you consider `getQuery<xxx>(event)` ?

**Comment by oleghalin** [comment]
@pi0 is there any reason why getQuery doesnt accept generics? If no any problems with it i will be happy to contribute for this

**Comment by maicss** [comment]
It's sooo ugly, should unknow first.
```
const query = getQuery(event) as unknown as Query;
```

**Comment by oleghalin** [comment]
> It's sooo ugly, should unknow first.
> 
> ```
> const query = getQuery(event) as unknown as Query;
> ```

I think as soon as Query implements `Record<string, unknown>` assigning it to getQuery is ok, but i can be wrong

**Comment by pi0** [comment]
PR welcome to support generic type 🙏

**Comment by NozomuIkuta** [comment]
This issue can be fixed at 2 layers:

- ufo
  - Fix `getQuery` to accept generics, which will be fixed by https://github.com/unjs/ufo/pull/131
  - Release it
- h3
  - Upgrade ufo version
  - Fix `getQuery` to accept generics and pass it to the upgraded ufo's `getQuery`

**Comment by pi0** [comment]
ufo generic support released and h3 support landing via https://github.com/unjs/h3/pull/417 in next release 🚀
