### ISSUE TITLE
async handle did not wait for closing

### ISSUE THREAD

**Issue by xhebox** [unjs/h3#35]
Found while experimenting with nuxt3.

In my nuxt app, h3 will use a lazy/promisify/async middleware handle, which will eventually be invoked in `callHandle`:

https://github.com/unjs/h3/blob/2805d4cc42d22c22c7798a41514aca5cceeb8e19/src/handle.ts#L18-L21

But async function will return a promise instance, if async handler does not send/close the response before they return, `callHandle` resolve immediately.

The following patch is helpful on my case:

```
--- a/node_modules/h3/dist/index.mjs
+++ b/node_modules/h3/dist/index.mjs
@@ -109,7 +109,7 @@ function callHandle(handle, req, res) {
     const next = (err) => err ? reject(err) : resolve(void 0);
     try {
       const returned = handle(req, res, next);
-      if (returned !== void 0) {
+      if (returned !== void 0 && !(returned instanceof Promise)) {
         resolve(returned);
       } else {
         res.once("close", next);
```

Suspect it is root cause of #21.

**Comment by pi0** [comment]
In latest (0.8+) version of h3, you should explicitly convert legacy middleware using `h3.fromNodeMiddleware((req, res) => {})`.
