### ISSUE TITLE
Handle 404

### ISSUE THREAD

**Issue by lautiamkok** [unjs/h3#352]
### Describe the feature

It seems that h3 does not handle unknown routes at all. There is no documentation about it as well. If h3 can handle unknown routes, could you please provide us with some guides?

There is no doc on how to handle errors in general in h3 as well...

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Are you looking for a way to set a custom 404 error handler?

**Comment by lautiamkok** [comment]
@pi0 I have no idea how to do it in h3. We can do it in Koa.js just with a middleware as follows:

```
// https://github.com/koajs/koa/wiki/Error-Handling
export default async (ctx, next) => {
  await next()

  // Handle 404 - throw it as an error.
  if (ctx.status === 404) {
    ctx.throw(404, 'Page not found')
  }
}

```

**Comment by lautiamkok** [comment]
I worked it out finally. cheers
