### ISSUE TITLE
Add `onResponse` callback to `sendProxy` and `proxyRequest` 

### ISSUE THREAD

**Issue by enkot** [unjs/h3#354]
### Describe the feature

Sometimes it is necessary to add/modify headers for proxy response. For example, we need to add some header or remove `secure` attribute from the cookie.
I suggest to add `onResponse` callback to `sendProxy` and `proxyRequest` (similar to `onProxyRes` in the `http-proxy`), which takes proxy `event` as argument, so we can do:
```ts
return proxyRequest(event, target, {
  headers,
  onResponse(_event) {
    setHeader(_event, 'foo', 'bar')
  }
})
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by oleghalin** [comment]
I think its better to upgrade `proxyRequest` to make it return modified response instead of sending response directly from method. @pi0

**Comment by enkot** [comment]
@pi0 Can you please share your thoughts on this?
