### ISSUE TITLE
proxyRequest should be able to proxy streams

### ISSUE THREAD

**Issue by iainsproat** [unjs/h3#373]
### Describe the feature

Attempting to proxy a request with a stream using `proxyRequest` currently fails as the body is incorrectly read.

For example, the following will not result in the expected body value of `This is a streamed request` reaching the `/debug` path:

```typescript
app.use(
        "/",
        eventHandler((event) => {
          return proxyRequest(event, url + "/debug", { fetch });
        })
);
      
const stream = new ReadableStream({
        start(controller) {
          controller.enqueue("This ");
          controller.enqueue("is ");
          controller.enqueue("a ");
          controller.enqueue("streamed ");
          controller.enqueue("request.");
          controller.close();
        },
      }).pipeThrough(new TextEncoderStream());

      const result = await fetch(url + "/", {
        method: "POST",
        body: stream,
        headers: {
          "content-type": "application/octet-stream",
          "x-custom": "hello",
        },
        duplex: "half",
      }).then((r) => r.json());
```

### Additional information

- [X] Would you be willing to help implement this feature?

I have provided a rough outline of the problem and potential solution in https://github.com/unjs/h3/pull/374

**Comment by pi0** [comment]
This is opt-in supported via #413 please check nightly channel in readme if you like to early test.
