### ISSUE TITLE
Option to provide non-wrapped version of error (onError).

### ISSUE THREAD

**Issue by beganovich** [unjs/h3#377]
### Describe the feature

Hi,

I've been implementing a custom error handler using `onError` and it works fine, except for one part.  Since every error is wrapped using H3Error class, code like this isn't possible:

```ts
class CustomError extends Error {}

const app = createApp({
  onError(error, event) {
    if (error instanceof CustomError) {
      // ..
    }
  },
});
```

This would be super useful in case of custom validation error handling, for example, `ZodError` class. The key part missing is `instanceof` since each error is wrapped using H3 (https://github.com/unjs/h3/blob/main/src/error.ts#L55).

I was wondering, is there interest in providing an option to `AppOptions` for "vanilla" error classes?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi and thanks for the suggestion. I think it is really valid cause to have the need of accessing the original error object. As a more generic fix, i think we can make original error accessible from wrapped object.
