### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Promise

### ISSUE THREAD

**Issue by rafaeldsousa** [unjs/h3#381]
### Environment

node: v16.17
nuxt: 3.4.2
nitro: 2.3.3

### Reproduction

Nuxt API requests using useAsyncData + $fetch in frontend and server api uses `await readBody`

### Describe the bug

frontend request
```js
const body = { params: { ...route.query } }

const { data, error } = await useAsyncData(
    'server-api',
    () => $fetch('/api/server-api', { method: 'post', body: body }),
    {
        initialCache: false
    }
).catch((e) => console.error(e))
```

server API composable
```js
export default defineEventHandler(async (event) => {

    const body = await readBody(event)
}
```

### Additional context

Same issue as described here https://github.com/unjs/h3/commit/19d133d by many others. 
This latest release `1.4.0` seems to break things.

There is a workaround but it doesn't feel like something we'd actually want to be doing all over projects.
https://github.com/unjs/h3/commit/19d133d#r109674536

### Logs

```sh
[nuxt] [request error] [unhandled] [500] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Promise
```

**Comment by danielroe** [comment]
Would you be able to provide a reproduction? 🙏

**Comment by rafaeldsousa** [comment]
@danielroe this would be sort of a clone in terms of npm packages and env setup I have, but I cannot reproduce the issue on codesandbox. (note I have some `resolutions` on `package.json` to force some version to what I have locally)
https://codesandbox.io/p/sandbox/hellow-rkt3in

Locally and on the azure server we use I can definitely still reproduce the issue when I upgrade to 1.6.4. (Video below)

https://user-images.githubusercontent.com/39249777/235794974-f6d3ccd7-4b91-4e81-9d1b-08a4cb4c3fd9.mp4

**Comment by igorjacauna** [comment]
I used [this](https://github.com/unjs/h3/commit/19d133d6a33ffb742713f4d83f00f555aeb83224#r109674536) workaround, in commit that @so1ve mentioned, to make work my api routes. But, api routes created by libs like `nuxt-vuefire` for example, that has not the workaround implemented, throw the error.

**Comment by danielroe** [comment]
@so1ve so is the issue resolved now?

**Comment by so1ve** [comment]
> @so1ve so is the issue resolved now?

I'm not sure. In my use case (nuxt) the issue is resolved, but h3 users may not.

**Comment by igorjacauna** [comment]
Hi @danielroe ,

I just run `npx nuxi@latest upgrade --force` and the Nuxt is in 3.5.2. 

> I got error about [this](https://github.com/nuxt/nuxt/issues/13866) issue that block my build. So, I removed `yarn.lock` and reinstall. And this time the build works.

Locally, the requests works fine. But in Firebase, where I deployed my application, shows:

```
The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
```

The workaround still works:

```ts
// @ts-expect-error - req.body is not defined in the type definitions
const body = await (event.node.req.body || readBody(event));
```

**Comment by igorjacauna** [comment]
@danielroe , just created this Nuxt project with `npx nuxi@latest init app`: https://github.com/igorjacauna/issue-readbody

After deploy to Firebase, should show error when try to make a POST request to `/api/issue` with a body in request

**Comment by sisou** [comment]
Thanks @igorjacauna for the repro!

It even works without deploying to Firebase. Just add `firebase-tools` as a dependency, and you can run and reproduce it in the emulator:

```bash
yarn add --dev firebase-tools
NITRO_PRESET=firebase yarn build
yarn firebase emulators:start --only functions,hosting

# From another terminal:
curl -X POST 'http://localhost:5000/api/issue' -H 'Content-Type: application/json' --data-raw '{"test":1}'
```

**Comment by pi0** [comment]
Another related fix where firebase parses form-data requests as object into `req.body`: https://github.com/unjs/h3/pull/604
