### ISSUE TITLE
[nuxt] proxyRequest with multiple 'set-cookie' headers gets merged into one header

### ISSUE THREAD

**Issue by Mokkapps** [unjs/h3#384]
### Environment

Nuxt: 3.4.3
Node: 18.14.2

### Reproduction

https://stackblitz.com/github/Mokkapps/nuxt-multiple-set-cookie?file=server/api/upstream.ts

## Current Behaviour

Only one `set-cookie` is returned from the `proxyRequest` response: 

```ts
export default defineEventHandler((event) => {
  return proxyRequest(
    event,
    "https://7dzqb4dvrf.execute-api.eu-central-1.amazonaws.com/dev"
  );
});
```

The endpoint response which contains multiple `set-cookie` response headers: 

![image](https://user-images.githubusercontent.com/3127210/237054316-311368d3-a0d8-4bd8-8ce8-d2744943c2a3.png)

The `proxyRequest` response only contains the last `set-cookie` header:

![image](https://user-images.githubusercontent.com/3127210/237054628-df0c6244-eda0-44fb-9765-4d082457f5af.png)

## Expected Behaviour

`proxyRequest` proxies all `set-cookie` response headers

**Comment by PunkPengu** [comment]
same problem here :( hope it will get fixed soon!

**Comment by oleghalin** [comment]
See https://github.com/unjs/nitro/pull/989

**Comment by pi0** [comment]
Hi. For proxy we do split cookies but there was a bug with node fetch (https://github.com/unjs/h3/pull/408).

Please let me know if this still needs investigation in h3. (nitro PR is separate issue to track)
