### ISSUE TITLE
Use `Symbol.from` instead of internal flags

### ISSUE THREAD

**Issue by zuixinwang** [unjs/h3#389]
### Environment

![1684408335474](https://github.com/unjs/h3/assets/59717852/e5e0f861-390e-4603-bc44-64c6fd27d8e2)

Aha, This is not a bug, but I think using Symbol is better. 😃 

### Reproduction

See the Environment part.

### Describe the bug

See the Environment part.

**Comment by pi0** [comment]
Hi. It is mainly to handle multiple builds of h3 to not use symbols. However we might use `Symbol.from` to leverage global registry. PR is welcome 🤔

**Comment by zuixinwang** [comment]
Aha, do you mean [`Symbol.for()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for)? 😃

**Comment by pi0** [comment]
Hi dear @zuixinwang while triaging i just reminded this issue again. I think it could be a really good idea if we did it at first to leverage Symbol.for (beck in time there was lack of runtime support).

At this stage, there are not much benefits for the switch from internal flag to symbol but it can potentially make issues if an event is being created by an older version of h3 and being consumed in newer one. we need additional backward compatibility check in place and it is not also possible other way around (new h3 event consumed by older h3 handler)

I think will keep this in my mind for major future versions but at this point, closing issue from tracker.

Thanks again for bringing suggestion please do it again ❤️
