### ISSUE TITLE
Documentation/example of how to run h3 in a worker environment

### ISSUE THREAD

**Issue by JamieCurnow** [unjs/h3#39]
I'm trying to get started with h3 in a Cloudflare worker - are there any examples of how to get started with h3 in workers?

```
import { createApp } from 'h3'

const app = createApp()
app.use('/', () => 'Hello world')

addEventListener('fetch', (e) => {
  // ???
})
```

**Comment by JamieCurnow** [comment]
@pi0 Thank you for pointing me in the right direction! You're right - it's not straightforward at the moment 😅

I managed to figure it out though and made a little helper package that wraps around h3's createApp and exposes a function to handle the fetch event from Cloudflare.

In case anyone else is trying to do this too check out:
https://github.com/JamieCurnow/h3-worker#readme

Needs a good test, but is working for my use case. Suggestions/questions/pull requests are welcome as always :)

**Comment by jontybrook** [comment]
@JamieCurnow thanks for this, helped me out a lot!

**Comment by renhiyama** [comment]
@pi0 can we expect docs anytime soon on this?

**Comment by Hebilicious** [comment]
Pending until we have full Response/Request support
