### ISSUE TITLE
Can custom error response?

### ISSUE THREAD

**Issue by mengdu** [unjs/h3#392]
### Describe the feature

Can custom error response?

current:

```json
{
    "url": "/api/test",
    "statusCode": 500,
    "statusMessage": "",
    "message": "Hi, error!",
    "stack": "xxxx"
}
```

expect:

```json
{
 "ret": -1,
  "msg": "unkonw",
  "stack": "xxx"
}
```

Can it be achieved？

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by maou-shonen** [comment]
If you use nuxt or nitro -> [custom-error-handler](https://github.com/unjs/nitro/tree/main/examples/custom-error-handler)
use only h3 -> app,.options.onError
