### ISSUE TITLE
"How It Works" link not working on README

### ISSUE THREAD

**Issue by hjb1694** [unjs/h3#396]
### Describe the feature

I would like to see how the route-specific middlewares work, but when I click the "How It Works" link, it does nothing. Is there a guide on how to implement middleware for routes?

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by hjb1694** [comment]
I want to share my own solution I created for the meantime:

`
type MiddlewareFn = (ctx: object, next: Function) => void | Promise<void>;

class MiddlewarePipeline {

    stack: MiddlewareFn[] = []

    constructor(private middlewares: MiddlewareFn[]){
        this.stack = middlewares;
    }

    public append(middlewareFn: MiddlewareFn | MiddlewareFn[]) {

        function throwIncorrectTypeError(): never {
            throw new Error('Argument must be a middleware function or an array of middleware functions.');
        }

        if(Array.isArray(middlewareFn)){
            for(let fn of middlewareFn){
                if(typeof fn !== 'function'){
                    throwIncorrectTypeError();
                }else if(fn.length !== 2){
                    throwIncorrectTypeError();
                }
            }
            this.stack = [...this.stack, ...middlewareFn]
        }else if(typeof middlewareFn === 'function'){
            if(middlewareFn.length !== 2){
                throwIncorrectTypeError();
            }
            this.stack = [...this.stack, middlewareFn]
        }else{
            throwIncorrectTypeError();
        }

    }


    public async execute(context: object) {

        let prevIdx = -1;

        const runner = async (idx: number) => {

            if(idx === prevIdx) {
                throw new Error('Next function called more than once.');
            }

            prevIdx = idx;

            const middleware = this.stack[idx];

            if(middleware !== undefined){
                await middleware(context, () => {
                    return runner(idx + 1);
                });
            }

        }

        await runner(0);


    }

}


export default MiddlewarePipeline;
`


For the route:


`
import MiddlewarePipeline from './app';

import { createRouter, defineEventHandler, useBase } from 'h3';

const router = createRouter();

router.get('/', defineEventHandler(event => {

    const context = {event}

    const one = (ctx, next) => {
        console.log('one');
        next();
    }
    const two = async (ctx, next) => {
    
        const doThis = () => {
            return new Promise((resolve, reject) => {
            setTimeout(() => {
                console.log('two');
                resolve('boom!');
            }, 3000);
            });
        }
    
        await doThis();
        next();
    
    }
    const three = (ctx, next) => {
        console.log('three');
        next();
    }

    new MiddlewarePipeline([one, two, three]).execute(context)

    return {message: 'Boom!'}
}))


export default useBase('/api/helloworld', router.handler);
`

**Comment by pi0** [comment]
Thanks for notice. I have updated link in readme to the source code for now. PR is more than welcome to improve docs explanation.
