### ISSUE TITLE
matchParams() utility

### ISSUE THREAD

**Issue by pi0** [unjs/h3#4]
A match factory utility to match params (`/[user]/[foo?]/`) ~~and populate `req.params`~~

**Comment by Atinux** [comment]
This library looks nice: https://github.com/snd/url-pattern

**Comment by ricardogobbosouza** [comment]
I believe this library is better maintained
https://www.npmjs.com/package/path-to-regexp

**Comment by posva** [comment]
This is definitely something I can and want to help with 🙂

**Comment by byronferguson** [comment]
> I believe this library is better maintained https://www.npmjs.com/package/path-to-regexp

According to Express.js documentation, this is exactly the library they use to define regex for path definitions.

They even link a tool for testing paths: http://forbeslindesay.github.io/express-route-tester/

**Comment by pi0** [comment]
Adding initial router support with #64.

---

Why not go with the matching pattern as initially proposed: More thinking, route matching could be expensive if we lookup all middleware. Using a router we could also properly throw 404/405 error when route or method are not matching
