### ISSUE TITLE
useBody with `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by mirabledictu** [unjs/h3#40]
Hello, when using `useBody` I get a string instead of an object. Something like this `field=value&another=value`. Is there an option to make this an object? What I currently do is this:

```ts
let body = await useBody(req)
body = Object.fromEntries(new URLSearchParams(body))
```

thanks

**Comment by walmartwarlord** [comment]
This is working now

**Comment by NozomuIkuta** [comment]
@pi0 

As @walmartwarlord said, you already released this feature as a part of v0.5.3.

https://github.com/unjs/h3/blob/v0.5.3/CHANGELOG.md#053-2022-03-31 

So you could close this issue, or is there any remaining issues in your mind?

**Comment by AustinGil** [comment]
I have not tested in the project yet, but I dont think [this solution](https://github.com/unjs/h3/blob/ac5432f38c7902c107c048b2f8c9f767a567c1c1/src/utils/body.ts#L67) works properly for all use cases. With URLSearchParams, it's possible to have multiple values for the same key, but with objects, you would overwrite the data. This would cause data loss. Also, the values in URLSearchParams will always return strings, which isn't the case for Objects.

For example:

```js
const d = new URLSearchParams([['a', 1],['a', 2]])
const o = Object.fromEntries(d.entries())

console.log(d.getAll('a')) // returns ['1', '2']
console.log(o['a']) // returns 2
```

The best solution I've found is to use the "[qs](https://www.npmjs.com/package/qs)" package:

```js
if (headers['content-type']?.includes('application/x-www-form-urlencoded')) {
  body = qs.parse(body);
}
```

**Comment by AustinGil** [comment]
Have confirmed that the current solution causes data loss.

When you submit this form: 

```html
<form>
  <input name="name" value="1" />
  <input name="name" value="2" />
  <button>Submit</button>
</form>
```

`await readBody(event)` returns this data

```json
{
  name: '2'
}
```

The expected data should be something like:
```json
{
  name: ['1', '2']
}
```

This can be accomplished with the `qs` package:

```js
let body
if (headers['content-type']?.includes('application/x-www-form-urlencoded')) {
  body = qs.parse(await readRawBody(event));
}
```

**Comment by maximilliangeorge** [comment]
This only seems to work when `Content-Type` is exactly `application/x-www-form-urlencoded`. I'm currently having issues when parsing a request from a webhook that uses `application/x-www-form-urlencoded; **charset=UTF-8**`

**Comment by efraimbart** [comment]
> This only seems to work when `Content-Type` is exactly `application/x-www-form-urlencoded`. I'm currently having issues when parsing a request from a webhook that uses `application/x-www-form-urlencoded; charset=UTF-8`. When omitting `charset=UTF-8` the body is parsed as expected.

I'm having this issue as well. Is this the expected behavior?
