### ISSUE TITLE
Type and Runtime validated request utils

### ISSUE THREAD

**Issue by pi0** [unjs/h3#402]
Currently, we have utils such as `readBody(event)` and `getParams(event)` which both have any or unspecific types and have no runtime validation.

The idea is to expose request utils that are both **runtime** and **type** safe.

We might expose some core request validation utils (that require a custom validator function and have default strict `unknown` type) + `h3/zod` integration that provides them.

Current solutions:
- [h3-zod](https://github.com/wobsoriano/h3-zod) by @wobsoriano ❤️ 
- [h3-typebox](https://github.com/kevinmarrec/h3-typebox) by @kevinmarrec ❤️

Related discussions:
- #129
- #386 / #387

**Comment by Hebilicious** [comment]
We could accept a validator function as the 2nd argument. Then`h3/zod` or `h3/typebox` can directly integrate. 

```ts 
import { validator } from h3/zod
 const bodySchema = z//...
 const paramSchema = z//...
 const body = await readBody(event, validator(bodySchema, (result) => { if(!result.sucess) return createError() })) 
 const params = await getParams(event, validator(paramSchema, (result) => { if(!result.sucess) return createError() })) 
```

Btw we could add `readParams` for consistency.

**Comment by wobsoriano** [comment]
Saw this package that might be helpful - https://github.com/decs/typeschema

Basically allows you to use any validation library you want:

```ts
import type { Infer, Schema } from '@decs/typeschema';
import { assert}  from '@decs/typeschema';

// Use your favorite validation library, e.g. `zod`, `arktype`, `typia`
const schema: Schema<string> = z.string();
const schema: Schema<string> = type('string');
const schema: Schema<string> = typia.createAssert<string>();

// Extracts the schema type
type Type = Infer<typeof schema>; // `string`
```

**Comment by Hebilicious** [comment]
> Saw this package that might be helpful - [decs/typeschema](https://github.com/decs/typeschema)
> 
> Basically allows you to use any validation library you want:
> 
> ```ts
> import type { Infer, Schema } from '@decs/typeschema';
> import { assert}  from '@decs/typeschema';
> 
> // Use your favorite validation library, e.g. `zod`, `arktype`, `typia`
> const schema: Schema<string> = z.string();
> const schema: Schema<string> = type('string');
> const schema: Schema<string> = typia.createAssert<string>();
> 
> // Extracts the schema type
> type Type = Infer<typeof schema>; // `string`
> ```

This is absolutely great. We can have something like this that works with every validation library. 

```ts
 const body = await readBody(event, validator(schema, (error) => createError())) 
```

@wobsoriano do you have another suggestion for the API design ?

**Comment by wobsoriano** [comment]
@Hebilicious assuming `validator` function in there accepts different validation libraries, it looks good!

**Comment by Hebilicious** [comment]
@wobsoriano It does ! Look at #431
