### ISSUE TITLE
New version "v1.7.0" does not export "splitCookiesString" function

### ISSUE THREAD

**Issue by martinsjek** [unjs/h3#412]
### Environment

Node 18.16

### Reproduction

`import { splitCookiesString } from 'h3';`

### Describe the bug

After update from v1.6.6 -> v1.7.0 build fails because my code fails to import:
`import { splitCookiesString } from 'h3';`

**Comment by pi0** [comment]
Hi. Thanks for reporting however checking published package, it seems `splitCookiesString` export is there (check last line in https://unpkg.com/browse/h3@1.7.0/dist/index.mjs)

Would be nice if you can share a reproduction if still having some issues would be happy to help 🙏🏼
