### ISSUE TITLE
Documentation, Website, Examples

### ISSUE THREAD

**Issue by Hebilicious** [unjs/h3#418]
### Describe the feature

While the README helps, h3 could definitely use a dedicated unjs website with proper documentation.

New Nuxt users don't have the best on-boarding experience, and pretty much have to go through the source code to understand a lot of things. 

We should also work toward enabling users that want to use H3 outside of Nuxt/Nitro, which similar to something like https://github.com/honojs/hono

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
#340

**Comment by pi0** [comment]
Let's track via #340. I will add more information there about the docs plan.
