### ISSUE TITLE
[helpers] add missing helpers 

### ISSUE THREAD

**Issue by Hebilicious** [unjs/h3#420]
### Describe the feature

Some helpers that are missing from h3, and require users to explicitly rely on `event.node`. 

We should provide the following helpers as a part of the migration to  #73 

Once everything is covered, we can start deprecating `event.node` usage for end-users, as they should not rely on node agnostic API for their needs.

Header : 
- removeResponseHeaders
- removeResponseHeader
- getRequestRawHeader
- getResponseHeaders
- getResponseHeader

Response : 
- sendResponse

URL : 
- setOriginalUrlPath
- getOriginalUrlPath
- setUrlPath
- getUrlPath
- getRequestPath

Note specific :
- nodeResWritableEnded (event.node.res.writableEnded)

Reference for implementation and test https://github.com/Hebilicious/h3/pull/2/files

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I think now we have most missing utils as `event.[]` props. Let's see what is missing in the future.
