### ISSUE TITLE
[feature] implement adapters

### ISSUE THREAD

**Issue by Hebilicious** [unjs/h3#425]
### Describe the feature

Implement adapters to provide a straightforward way to use h3 with other frameworks / platforms without Nitro

NodeJS based : 
- Node.js
- Fastify

Fetch based : 

- Cloudflare 
- Deno
- Bun

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
This is a nice idea but both are in scope of https://nitro.unjs.io/ to support framework and provider presets. H3 shall remain a thin and abstracted layer targerring Node.js and Webstandards.

**Comment by redbar0n** [comment]
@pi0 But the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) _is_ a web [standard](https://fetch.spec.whatwg.org/#fetch-method)? If you follow the [WinterCG standard](https://wintercg.org/) then H3 could support all of these, no?

**Comment by redbar0n** [comment]
https://h3.unjs.io/adapters/bun
