### ISSUE TITLE
Accept File upload! 

### ISSUE THREAD

**Issue by folamy** [unjs/h3#43]
How do I use h3 to get files from client/browser for file upload?
I am coming from ExpressJs, where I can install a package called express-fileupload.
Link:
[Express Fileupload](https://www.npmjs.com/package/express-fileupload) 
```js
const express = require('express');
const fileUpload = require('express-fileupload');
const app = express();
app.use(fileUpload())
Then 
app.post ('/someApi' , (req, res) =>{
   console.log(req.files)
})
```

**How do I achieve this?**

**Comment by folamy** [comment]
Sorry, I forgot to mention that I am using nuxt 3!

**Comment by wobsoriano** [comment]
Then do it like this?

```ts
import type { IncomingMessage, ServerResponse } from 'http'

const form = formidable({ multiples: true })

export default async (req: IncomingMessage, res: ServerResponse) => {
    form.parse(req, (err, fields, files) => {
        // do something
    })

    // return
}
```

**Comment by folamy** [comment]
> Then do it like this?
> 
> ```ts
> import type { IncomingMessage, ServerResponse } from 'http'
> 
> const form = formidable({ multiples: true })
> 
> export default async (req: IncomingMessage, res: ServerResponse) => {
>     form.parse(req, (err, fields, files) => {
>         // do something
>     })
> 
>     // return
> }
> ```

@wobsoriano, do you know how I can integrate socketio with nuxt3?
My major challenge is that I don't have access to the main server instance.

**Comment by bfg-coding** [comment]
How are you guys sending the data from client? I've been trying to get a image file to transfer to the server side and I'm just not getting it there. I'm not sure what I'm missing

**Comment by wobsoriano** [comment]
> How are you guys sending the data from client? I've been trying to get a image file to transfer to the server side and I'm just not getting it there. I'm not sure what I'm missing

Using https://developer.mozilla.org/en-US/docs/Web/API/FormData

**Comment by bfg-coding** [comment]
@wobsoriano Thank you, I found that earlier so it's good to hear I'm on the right track. Here is my current setup

Client
``` ts
const fd = new FormData();
    fd.append("name", fileName);
    fd.append("image", file);

    axios.post("/api/avatars", fd, {
      headers: {
        'accept': 'application/json',
        'Accept-Language': 'en-US,en;q=0.8',
        'Content-Type': `multipart/form-data; boundary=${file._boundary}`,
      }
    }).then(resp => { console.log(resp)});
```

Nuxt3 `server/api/avatars`
```ts
import {IncomingMessage, ServerResponse} from "http";
import formidable from "formidable";

const form = new formidable.IncomingForm();

export default async (req: IncomingMessage, res: ServerResponse) => {
    form.parse(req, async (err, fields, files) => {
        console.log(err);
        console.log(fields);
        console.log(files);
    })
    res.end("Got data");
}
```

The error I'm getting now is 
```
 ERROR  [proxy] write EPIPE                                                                                                                                                                                                                                                                                                                                                                                                                                    

  at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
```

I'd appreciate your continue help as I've been stuck on this for a day and a half now. 

Thank you

**Comment by thingsneverchange** [comment]
The last comment was left back 4 months ago, but @[bfg-coding](https://github.com/bfg-coding) this happened to me too today. What I noticed in the document from Fromdable was they wrapped the form parse function in the promises. 

Without it, that's what I encountered
```
 ERROR  [proxy] write EPIPE                                                                                                                                                                                                                                                                                                                                                                                                                                    

  at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:98:16)
```

So the final code should be :

```

export default async (req, res) => {

  const form = formidable({ multiples: true });

    await new Promise((resolve, reject) => {
      form.parse(req, (err, fields, files) => {
        console.log(files]
      });
    });

    return {}

}
```

And I get this:

```
{
  image: [
    PersistentFile {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      lastModifiedDate: 2022-03-16T14:56:34.284Z,
      filepath: '/var/folders/93/m7bwg2ds5gzf4w35bctsb1k40000gn/T/eff7ead095d57e3ed63a44900',
      newFilename: 'eff7ead095d57e3ed63a44900',
      originalFilename: '1.jpeg',
      mimetype: 'image/jpeg',
      hashAlgorithm: false,
      size: 317210,
      _writeStream: [WriteStream],
      hash: null,
      [Symbol(kCapture)]: false
    }
  ]
}
```

Hope this helps some newbies like me guide to the backend world of node frameworks.

**Comment by joseph-montanez** [comment]
> Partially related, but how do you guys serve the uploaded file using `h3` handler?
> 
> I'm trying:
> 
> ```
> // server/api/file.ts
> 
> import type { ServerResponse } from "http";
> import { CompatibilityEvent } from "h3";
> import fs from "fs";
> 
> export default async (event: CompatibilityEvent, res: ServerResponse) => {
>   const filename = "./uploads/file.jpg";
> 
>   const readStream = fs.createReadStream(filename);
> 
>   readStream.on("error", function (err) {
>     console.log(`error: ${err.message}`);
>     res.end(err.message);
>   });
> 
>   readStream.on("open", function () {
>     res.statusCode = 200;
>     readStream.pipe(res);
>   });
> };
> ```
> 
> But it gives 404 error:
> 
> ```
> {
> "url": "/api/file",
> "statusCode": 404,
> "statusMessage": "Not Found",
> "message": "Not Found"
> }
> ```
> 
> Also asked at `Nuxt 3` [nuxt/framework#4299](https://github.com/nuxt/framework/discussions/4299) and found similar question at `h3` #93

Here is what worked for me:

**Front-end**
```ts
      const images = imagesElem.value.$el.parentNode.querySelector('input[type=file]');
      const data = new FormData();

      data.append('id', unref(penTablet).id);
      for (let i = 0; i < images.files.length; i++) {
        const image = images.files[i];
        data.append(`images[${i}]`, image);
      }

      const imagesResult = await $fetch('/api/admin/pen-tablets/images', {
        method: 'post',
        body: data
      });
```

**Backend**
```ts
// api/admin/pen-tablets/images.post.ts

import {CompatibilityEvent, defineEventHandler, sendStream, useQuery} from "h3";
import formidable from "formidable";

export default defineEventHandler(async (event: CompatibilityEvent) => {
    const form = formidable({ multiples: true });

    form.parse(event.req, (err, fields, files) => {
        console.log(err, fields, files);
        const id = fields.id; // Item ID
        
        event.res.end(JSON.stringify({
            success: true,
            message: '',
        }));
    });

    return sendStream(event, event.res);
});
```

This is the console log result:

```
null { id: 'huion-inspiroy-hs610' } {
  'images[0]': PersistentFile {
    _events: [Object: null prototype] { error: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    lastModifiedDate: 2022-07-12T02:23:32.226Z,
    filepath: '/var/folders/fy/1ldz3hw90gj92jzd9q4zw8mr0000gn/T/e9c47b3b49564c0913e8e2600',
    newFilename: 'e9c47b3b49564c0913e8e2600',
    originalFilename: '51vulWhPVIL._AC_SL1500_.jpg',
    mimetype: 'image/jpeg',
    hashAlgorithm: false,
    size: 25332,
    _writeStream: WriteStream {
      fd: 137,
      path: '/var/folders/fy/1ldz3hw90gj92jzd9q4zw8mr0000gn/T/e9c47b3b49564c0913e8e2600',
      flags: 'w',
      mode: 438,
      start: undefined,
      pos: undefined,
      bytesWritten: 25332,
      closed: false,
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      [Symbol(kFs)]: [Object],
      [Symbol(kIsPerformingIO)]: false,
      [Symbol(kCapture)]: false
    },
    hash: null,
    [Symbol(kCapture)]: false
  }
}
```

**Comment by Lyokolux** [comment]
> 

I am using:

```typescript
import fs from 'fs'
import { sendStream } from 'h3'
import { getFilepathFromId } from '~/server/lib/fileStorage'

export default defineEventHandler(async (event) => {
  const fileId = event.context.params.media
  const filepath = getFilepathFromId(fileId)

  return sendStream(event, fs.createReadStream(filepath))
})
```

It works perfectly except for Safari video streaming that I am currently debugging.

**Comment by a-toms** [comment]
Here's a tangential tutorial that is helpful: https://blog.replit.com/build-a-speech-to-text-app-with-assemblyai-on-replit

**Comment by madebyfabian** [comment]
For everyone refering to this issue, I actually had to remove the content-type header on the Client to make this work. Otherwise this happened: https://stackoverflow.com/questions/41138443/multipartparser-end-stream-ended-unexpectedly

So the updated **Client** example would be:
```ts
const fd = new FormData();
fd.append("name", fileName);
fd.append("image", file);

axios.post("/api/avatars", fd, {
  headers: {
    'accept': 'application/json',
    'Accept-Language': 'en-US,en;q=0.8',
  }
}).then(resp => { console.log(resp)});
```

**Comment by MickL** [comment]
Just to clarify for everyone coming here: This can now be done easily:

```ts
const files = await readMultipartFormData(event);
```

Which returns an array of MultiPartData:

```ts
interface MultiPartData {
    data: Buffer;
    name?: string;
    filename?: string;
    type?: string;
}
```
