### ISSUE TITLE
readBody() does not take into account `application/x-www-form-urlencoded; charset=utf-8`

### ISSUE THREAD

**Issue by efraimbart** [unjs/h3#437]
If `charset=utf-8` is added to the content type `readBody()` will attempt to parse the body as json and fail. See
https://github.com/unjs/h3/blob/d11f817f1b18d5da6e311bdd0a222ae661efa2c2/src/utils/body.ts#L107-L115.

**Comment by Hebilicious** [comment]
I think we should support charset in the content type header by either extracting it first or using string.contains

**Comment by pi0** [comment]
Thanks for reporting issue. It will be resolved in next release by (4af66eb72a3b1ba0be311ac50a7668706a4e10df). I have added an internal comment that in next iterations, we might actually use the charset to handle encoding.
