### ISSUE TITLE
Allow hooking into responses

### ISSUE THREAD

**Issue by pi0** [unjs/h3#447]
Related: https://github.com/unjs/nitro/issues/1396

Currently, it is not possible to hook into responses (that are handled by h3 not directly with `res.end`). In order to do this, we might refactor `app.ts` and allow hooking into directly returned responses and allow to hook into using custom callback `onBeforeResponse(event, { body })`.

This can be later used by higher order frameworks to support custom response rewrite handling and logging. 

At this point, i also like to gether some common usecase ideas before moving forward (mainly because it also adds some overhead even if callback is not used)

**Comment by emdede** [comment]
Just had this today and my use-case would be custom error messages per "middleware" which afaik is currently not possible. Please correct me if I'm wrong.

```js
router.post('/', (event) => somethingThatPotentiallyErrors())

router.onBeforeResponse((event) => {
  if (event.data instanceof Error) return { status: 'error', message: event.data.message }
  return { status: 'ok', ...event.data }
}
```

**Comment by tobychidi** [comment]
It is needed for stuff like treblle-utils by [treblle.com](https://www.treblle.com/) . Then I feel like we are missing out? Cuz there is a solution for this in Express and Fastify.

**Comment by Hebilicious** [comment]
> It is needed for stuff like treblle-utils by [treblle.com](https://www.treblle.com/) . Then I feel like we are missing out? Cuz there is a solution for this in Express and Fastify.

I agree that this feature is needed, however looking at Trebble docs (for the first time); I think its possible to integrate it with h3 without hooking into the response.

Look at how the Koa integration is made.

**Comment by pi0** [comment]
Thanks for the feedbacks @Hebilicious, @emdede and @tobychidi ❤️ 3 hooks will be supported in next release (see #482)
