### ISSUE TITLE
Respond with a stream of data

### ISSUE THREAD

**Issue by educkf** [unjs/h3#45]
Hello!

Is there a way already to respond a request with a stream of data?

I am planning specifically to use puppeteer [page.createPDFStream](https://pptr.dev/#?product=Puppeteer&version=v11.0.0&show=api-pagecreatepdfstreamoptions), as Firebase Functions don't give us much initial memory, and I only found a way to increase it via regular cloud function, and not using nuxt `/server/api` folder.

So, probably in this case, stream the data would be a good fit.
Thanks a lot!

**Comment by harlan-zw** [comment]
related: https://github.com/unjs/h3/pull/68 ?
