### ISSUE TITLE
`proxyRequest()` doesn't take into account header casing when overriding headers.

### ISSUE THREAD

**Issue by efraimbart** [unjs/h3#450]
If a header is sent by the client with one casing and it's overridden with another in `proxyRequest` they'll both be sent.

https://github.com/unjs/h3/blob/a3192fb919034bb952f6b75271f50e4732ed7d8e/src/utils/proxy.ts#L42-L49

**Comment by pi0** [comment]
Thanks for the report. It will be fixed in the next release.
