### ISSUE TITLE
possible to delete a cookie?

### ISSUE THREAD

**Issue by acidjazz** [unjs/h3#46]
I tried setting `''` and `undefined` to `setCookie()` with no luck

**Comment by acidjazz** [comment]
Maybe by setting the maxAge to a negative number?

**Comment by danielroe** [comment]
Yes, you delete a cookie by setting its `maxAge` to `0` or even `-1`.

**Comment by danielroe** [comment]
@pi0  Shall we create a deleteCookie utility?

**Comment by pi0** [comment]
Yeah! Opened for adding deleteCookie. An alternative would be semantic delete flag like `setCookie(name, { delete: true })`

**Comment by HendrikJan** [comment]
Documentation about a "deleteCookie" function might be easier to find using a search engine than `setCookie(name, {delete: true})`. "deleteCookie" is also easier to read.
