### ISSUE TITLE
Transparently handle proxy errors

### ISSUE THREAD

**Issue by Aareksio** [unjs/h3#464]
### Describe the feature

https://github.com/Aareksio/reproduction-nitro-proxy-error/tree/main

When the request passing through proxy returns non-successful status code, the error is thrown. I would love to opt-in for fully transparent proxy, forwarding reply exactly as is. See reproduction for current and desired state, as well as simple workaround.

```ts
// nitro.config.ts
export default defineNitroConfig({
  routeRules: {
    '/': { proxy: { to: 'https://github.com/404' } },
  },
});
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by Aareksio** [comment]
@pi0 Do you want it to be transparent by default? Because otherwise this is already possible by
```ts
return proxyRequest(event, target, { fetchOptions: { ignoreResponseError: true } })
```

Sure this can be made into simpler API, but difference is subtle
```ts
return proxyRequest(event, target, { transparent: true })
```

On nitro level you can not do this without abusing types with `any`, therefore the [PR](https://github.com/unjs/nitro/pull/1489) made more sense.
If making this a default, I am worried the change should be considered breaking.

**Comment by pi0** [comment]
I think it is sensable that we keep the default `fetch` behavior _also_ for nitro and have constant one. I think we might also support a new dedicated flag like `catchErrors` that enables opt-in for this behavior (also for built-in fetch)
