### ISSUE TITLE
[ci] implement edge channel

### ISSUE THREAD

**Issue by Hebilicious** [unjs/h3#465]
### Describe the feature

Implement CI that publish h3 releases on each commit to main.
This is similar to what happens with Nitro.
As `edge` has become a very ambiguous term, we could consider another name, such as `nightly` or `canary`.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Tada! https://www.npmjs.com/package/h3-nightly

**Comment by Hebilicious** [comment]
Amazing ❤️ 
Should we change nitro name to nightly as well ? 🤔
