### ISSUE TITLE
Failed to upload images using postman's binary tool

### ISSUE THREAD

**Issue by lmq352489099** [unjs/h3#469]
### Environment

{
  "name": "nuxt-app",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "devDependencies": {
    "@bytemd/vue-next": "^1.21.0",
    "@nuxt/devtools": "latest",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@types/jsonwebtoken": "^9.0.2",
    "@types/node": "^18.16.19",
    "nuxt": "^3.3.1"
  },
  "dependencies": {
    "@bytemd/plugin-gfm": "^1.21.0",
    "@iconify/json": "^2.2.94",
    "@pinia/nuxt": "^0.4.11",
    "ali-oss": "^6.17.1",
    "ant-design-vue": "^3.2.20",
    "joi": "^17.9.2",
    "jsonwebtoken": "^9.0.1",
    "less": "^4.1.3",
    "md5": "^2.3.0",
    "mysql2": "^3.5.1",
    "pinia": "^2.1.4",
    "sass": "^1.64.1",
    "unplugin-icons": "^0.16.5",
    "unplugin-vue-components": "^0.25.1",
    "yarn": "^1.22.19"
  }
}

### Reproduction

```
   const client = new OSS({
      region: 'oss-cn-fuzhou',
      accessKeyId: 'xxxx',
      accessKeySecret: 'xxxx',
      bucket: 'j2-book',
    })
  const body = await readRawBody(event, 'binary')
  console.log('body :>> ', body);

  let { res: { requestUrls: [avatar] } } = await client.putStream('fileName1314',body )
```
  

----------------------------
  Failed to upload images using postman's binary tool

I'm not sure which step went wrong,

On the postman side, I use the readRawBody(event, 'binary') to receive the parameters and upload them to aliyun

On the postman side I use "readRawBody" to accept whether the data is correct

 

### Describe the bug

![image](https://github.com/unjs/h3/assets/37898934/e299c10d-662b-476a-a659-378b0cf7b07d)

### Logs

```sh
aliyun respone:
{
    "url": "/api/cos/uploadImage",
    "statusCode": 500,
    "statusMessage": "",
    "message": "stream.on is not a function",
    "stack": "<pre><span class=\"stack internal\">at destroyer (F:\\project-lmq\\learn-self-study\\bingo-book\\j2-book\\node_modules\\pump\\index.js:26:10)</span>\n<span class=\"stack internal\">at F:\\project-lmq\\learn-self-study\\bingo-book\\j2-book\\node_modules\\pump\\index.js:70:12</span>\n<span class=\"stack\">at Array.map (<anonymous>)</span>\n<span class=\"stack internal\">at pump (F:\\project-lmq\\learn-self-study\\bingo-book\\j2-book\\node_modules\\pump\\index.js:67:26)</span>\n<span class=\"stack internal\">at Client.putStream (F:\\project-lmq\\learn-self-study\\bingo-book\\j2-book\\node_modules\\ali-oss\\lib\\object.js:149:19)</span>\n<span class=\"stack\">at /F:/project-lmq/learn-self-study/bingo-book/j2-book/.nuxt/dev/index.mjs:995:16</span>\n<span class=\"stack internal\">at process.processTicksAndRejections (node:internal/process/task_queues:95:5)</span>\n<span class=\"stack internal\">at async Object.handler (/F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/h3/dist/index.mjs:1284:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/F:/project-lmq/learn-self-study/bingo-book/j2-book/node_modules/h3/dist/index.mjs:1359:7)</span></pre>"
}
```

**Comment by pi0** [comment]
Hi dear @lmq352489099. For `readRawBody`, you should pass `false` as second argument in order to access buffer. 

Please consider opening an issue in nuxt/nuxt repo with reproduction and ping me if still having questions or same issue on latest version 🙏🏼 (nuxt 3.6 with h3 1.8 is coming it contains another fix for streams it might resolve problems)
