### ISSUE TITLE
Add support for BigInt

### ISSUE THREAD

**Issue by bitbytebit1** [unjs/h3#474]
### Describe the feature

Currently if a BigInt needs to be sent to the client an error will be thrown.

```
[nuxt] [request error] [unhandled] [500] Do not know how to serialize a BigInt                                                                     1:31:58 PM
  at JSON.stringify (<anonymous>)  
  at Object.handler (./node_modules/h3/dist/index.mjs:1304:18)  
  at processTicksAndRejections (node:internal/process/task_queues:96:5)  
  at async toNodeHandle (./node_modules/h3/dist/index.mjs:1359:7)  
  at async ufetch (./node_modules/unenv/runtime/fetch/index.mjs:9:17)  
  at async $fetchRaw2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:206:26)  
  at async $fetch2 (./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs:239:15)  
```

Would love to see support for this!

One possible solution would be to use the reviver function. However I understand this would add complexity to both the sever and client. Wondering what the teams thoughts are regarding this functionality?

https://stackoverflow.com/questions/62539236/how-to-parse-a-json-data-type-bigint-in-typescript

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks for issue. It will be supported in next version.

**Comment by bitbytebit1** [comment]
Amazing! One step closer to the Nuxter role!

**Comment by chenneil69** [comment]
@pi0 Hello, thought this might help providing some info to your work. I am using h3@1.12.0 and it seems to still have the same issue..

```
 ERROR  [nuxt] [request error] [unhandled] [500] Do not know how to serialize a BigInt
  at JSON.stringify (<anonymous>)  
  at handleHandlerResponse (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2087:29)  
  at ./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:1983:15  
  at async Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:72:16)  
  at async Server.toNodeHandle (./node_modules/.pnpm/h3@1.12.0/node_modules/h3/dist/index.mjs:2266:7)
```

Thank you for any tips

**Comment by Urriel** [comment]
> ```ts
> type StringifyBigInt<T> = T extends bigint
>   ? string
>   : T extends (infer U)[]
>     ? StringifyBigInt<U>[]
>     : T extends object
>       ? { [K in keyof T]: StringifyBigInt<T[K]> }
>       : T;
> 
> export function stringifyBigInt<T>(body: T): StringifyBigInt<T> {
>   if (typeof body !== 'object' || body === null) {
>     return (typeof body === 'bigint' ? body.toString() : body) as StringifyBigInt<T>;
>   }
> 
>   if (Array.isArray(body)) {
>     return body.map(stringifyBigInt) as StringifyBigInt<T>;
>   }
> 
>   return Object.fromEntries(
>     Object.entries(body).map(([key, value]) => [key, stringifyBigInt(value)]),
>   ) as StringifyBigInt<T>;
> }
> ```

Your solution is not supporting Dates, this should fix the type issues.

```typescript
type StringifyBigInt<T> = T extends bigint
  ? string
  : T extends Date
    ? Date
    : T extends (infer U)[]
      ? StringifyBigInt<U>[]
      : T extends object
        ? { [K in keyof T]: StringifyBigInt<T[K]> }
        : T;

export function stringifyBigInt<T>(body: T): StringifyBigInt<T> {
  if (typeof body === 'bigint') {
    return body.toString() as StringifyBigInt<T>;
  }

  if (body instanceof Date || typeof body !== 'object' || body === null) {
    return body as StringifyBigInt<T>;
  }

  if (Array.isArray(body)) {
    return body.map(stringifyBigInt) as StringifyBigInt<T>;
  }

  return Object.fromEntries(
    Object.entries(body).map(([key, value]) => [key, stringifyBigInt(value)])
  ) as StringifyBigInt<T>;
}
```

**Comment by victorpagan** [comment]
This appears to still be an issue for both the client and server side when passing data containing BigInt. 

Minimal repo https://github.com/victorpagan/h3-unable-to-pass-or-receive-bigint

**Comment by victorpagan** [comment]
@Urriel how exactly was this added as a Nitro plugin? I'm running into this problem but it seems I have to switch between how the BigInt is serialized due to how it's handled in another SDK. I'm wondering if your solution could resolve this for my particular instance.

**Comment by pi0** [comment]
This issue was fixed to allow returning a BigInt value. 

Please refer to #995 for a follow-up conversation about returning objects with non-serializable values like BigInts.
