### ISSUE TITLE
Support server-sent-events

### ISSUE THREAD

**Issue by pi0** [unjs/h3#477]
Server sent events (https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) are an alternative to WS using long pooling connections in order to handle events.

**Comment by joshmossas** [comment]
In case anyone is looking for a solution right now I've published [h3-sse](https://github.com/joshmossas/h3-sse) an npm package that has server sent event utilities for H3.

It has all the same stuff in #586 but as a separate dependency until that PR gets merged or replaced by something better.

**Comment by pi0** [comment]
Landed via #386 as experimental feature and available in nightly channel thanks so much @joshmossas for helping on this! (some notes: https://github.com/unjs/h3/pull/586#issuecomment-1962736961)
