### ISSUE TITLE
useBody doesn't resolve Promise on local call when body is empty

### ISSUE THREAD

**Issue by Norel** [unjs/h3#49]
I tested with an api endpoint on a Nuxt3 project but you can probably reproduce with any local call I guess.

server/api/user.ts
```
export default async (req: IncomingMessage, res: ServerResponse) => {
    const body = await useBody(req)
}
```

Using ohmyfetch to call the api locally with default GET method (and without body)
```
await $fetch('/api/user')
```

The Promise in the useRawBody function never gets resolved because the req.on is never called https://github.com/unjs/h3/blob/25a61950f54fa1fe89b9d50fab71b3d040de0bf2/src/utils/body.ts#L29-L41

I guess it's tied to unenv fetch setting the req.body to null
https://github.com/unjs/unenv/blob/909d75e48667ce0732ce0fa8b6a2af4895f54d8e/src/runtime/fetch/call.ts#L31
```
req.body = context.body || null
```

I don't know if it's something that needs to be fixed here or in unenv.

As solution in h3 could be using this syntax (Node.js v10 + only) :
```
const bodyData = [];

for await (const chunk of req) {
    bodyData.push(chunk);
}

req[RawBodySymbol] = Buffer.concat(bodyData) 
resolve(encoding ? req[RawBodySymbol].toString(encoding) : req[RawBodySymbol]) 
```

**Comment by pi0** [comment]
Hi @Norel would you mind reporting this to [nuxt repo](https://github.com/nuxt/framework) with a minimal reproduction? local fetch (with unenv) in the latest version should directly be picked without going to events. You can try with `npx nuxi upgrade --force` to see if it fixes or not.
