### ISSUE TITLE
`fromWebHandler` adapter to use Request -> Response handlers with h3

### ISSUE THREAD

**Issue by nksaraf** [unjs/h3#490]
### Describe the feature

An adapte analogous to `fromNodeMiddleware` that adapts a `(request: Request) -> Response` handler to an h3 event handler

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Since h3 1.8 is web native, we have `event.request` (As normalized `Request` object) and we can directly return a `Reponse` from handlers. 

Making wrapper would be mainly a shortcut for translating `event.request` to `request` but i think it is still something nice for adapter to be supported.

**Comment by nksaraf** [comment]
Ohh wait i didnt know there was event.request and Response support already.. that makes things incredibly easier

**Comment by pi0** [comment]
Added in https://github.com/unjs/h3/commit/63050808141ac6e685be4cdf9f6e05cb770950a9
