### ISSUE TITLE
Support react pipeable streams

### ISSUE THREAD

**Issue by nksaraf** [unjs/h3#492]
### Describe the feature

Both `react`'s `renderToPipeableStream` and `solid-js`'s `renderToStream` return objects with just the `pipe` method as the stream response. `h3` looks for something with `pipe` and `_read` to detect a stream. This makes it so users have to patch whats returned by those libs with `_read` to make `h3` treat them like a stream response.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Thanks! Can you please manage to make a small stackblitz reproduction? 🙏🏼

**Comment by pi0** [comment]
Reproduction (and workaround): https://stackblitz.com/edit/github-1uqjco?file=app.ts&startScript=dev

```ts
  eventHandler((event) => {
    const el = createElement('h1', null, `Hello h3 + react!`);
    const stream = renderToPipeableStream(el);
    stream._read = () => {};
    stream.on = () => {};
    return stream;
  })
```
