### ISSUE TITLE
implement `getResponseCookie` and `parseResponseCookies`

### ISSUE THREAD

**Issue by Hebilicious** [unjs/h3#509]
### Describe the feature

https://github.com/nuxt/nuxt/pull/21940#issuecomment-1632784187

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by tobiasdiez** [comment]
The parsing added in https://github.com/unjs/nitro/pull/1753 could be reused here (and should be extracted to cookie-es for that purpose).

**Comment by pi0** [comment]
Upcoming h3 v2 will be based on web apis with `event.request.headers.getSetCookie()` 
 / `event.response.headers.getSetCookie()` 

Properly parsing `Set-Cookie` can be done with `parseSetCookie` in latest cookie-es package.
