### ISSUE TITLE
[question] Persist Session in Database à la express-session

### ISSUE THREAD

**Issue by angelhdzmultimedia** [unjs/h3#513]
Hello! I'm playing with `useSession` again! 😊

Question is, how to persist the session in database?

In express-session middleware, I would pass an instance of a Store that handles the persistance of the session in the library, which accept as options the database collection name to store the sessions into, and the ODM or ORM client to make the queries.
If I use Prisma with MongoDB, then the Store is @quixo3/prisma-session-store otherwise it's either connect-mongodb-session or connect-mongo.

How I would go about it with `useSession`? I really tried to find a way to do it myself, but didn't find anything other than the session's id...

Appreciate any tip, thank you.

**Comment by sisou** [comment]
Duplicate of #379.

**Comment by angelhdzmultimedia** [comment]
> Duplicate of #379.

Very kind. Thanks for the finding!
