### ISSUE TITLE
Add `getValidatedRouterParams(event, validate)`

### ISSUE THREAD

**Issue by Atinux** [unjs/h3#516]
### Describe the feature

Similar to `getValidatedBody(event, validate)` but for router params.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by Hebilicious** [comment]
We have `readValidatedBody` and `getValidatedQuery` and we could add a `getValidatedRouterParams` to get a typed result. 

On a s side note, I feel like we have some naming inconsistencies ;

- according to [express](https://expressjs.com/en/guide/routing.html) the precise terminology is route parameters
- we currently use both `readX` and `getX` ? Could we use `getX` for everything for the sake of consistencies?

**Comment by Barbapapazes** [comment]
> * we currently use both `readX` and `getX` ? Could we use `getX` for everything for the sake of consistencies?

Isn't a little nuance like explained here, https://stackoverflow.com/questions/23664175/whats-the-difference-between-read-readsome-get-and-getline?

**Comment by mynameisjeffe** [comment]
This would be a great feature to add. 
Right now I'm still using [h3-zod ](https://github.com/wobsoriano/h3-zod) primarily because **useValidatedParams**, which is pretty much the proposed **getValidatedBody(event, validate)**
