### ISSUE TITLE
Can the original exception be passed to the onError handler instead of H3Error? 

### ISSUE THREAD

**Issue by MarijnMensinga** [unjs/h3#517]
### Environment

1.8.0

### Reproduction

Throw any custom error inside of an eventHandler(). Example:
```javascript
class MyCystomError extends Error {
  public myCustomParam
  constructor(someParam){
     super("My custom error")
     this.myCustomParam = someParam
  }
}

export default defineEventHandler(async (event) => {
  throw new MyCystomError({myData:true})
})

```

### Describe the bug

The [app option "onError" handler](https://github.com/unjs/h3/blob/164f68e9cb89e011cd304dbe07b328611e3428a3/src/app.ts#L52) is not passed [the original error "_error"](https://github.com/unjs/h3/blob/164f68e9cb89e011cd304dbe07b328611e3428a3/src/adapters/node.ts#L59) but instead a [H3Error "error"](https://github.com/unjs/h3/blob/164f68e9cb89e011cd304dbe07b328611e3428a3/src/adapters/node.ts#L66C10-L66C46). 
This results in me not being able to access `error.myCustomParam` from my custom ErrorHandler.

Would it be OK to pass the oringal error? Since we could always wrap the original error into a H3Error if we want to?

**Comment by Harm-Nullix** [comment]
Another way to pass the original error along would be to include a `_rawError` or something like that to the H3Error that gets build.

That way, the original value `error` gets honoured but we can, in fact, find the original error.

@pi0 , @danielroe , what are your opinions on these kind of alterations on the code?

**Comment by pi0** [comment]
Hi @MarijnMensinga @Harm-Nullix Thanks for making an issue and explaining.

You can access the original error from the wrapped h3 error using `error.cause.myCustomParam`: 

(https://stackblitz.com/edit/github-rxhs8i?file=package.json,app.mjs&startScript=dev)

While this seems like adding a layer of wrapper, it is essential to ensure we can give a level of type and runtime level safety for thrown errors on received hooks.

**Comment by pi0** [comment]
Closing issue as is a current intentional behavior and you can leverage `error.cause` to access original. Would be happy to reopen and discuss if you still think it would be better to change.
