### ISSUE TITLE
`readMultipartFormData` problem on `Netlify`

### ISSUE THREAD

**Issue by becem-gharbi** [unjs/h3#533]
### Environment

Node `v18.17.1`
H3 `v1.8.1`
Nitropack `v2.6.3`
Preset `netlify`

### Reproduction

https://github.com/becem-gharbi/nitro-multipart

### Describe the bug

**Edit**: I'm not sure if this is related to `h3` or `nitropack`.

`readMultipartFormData` works on development as intended. However when running on Netlify it always returns an empty array.

```ts
export default eventHandler(async (event) => {
  const multipart = await readMultipartFormData(event);

  return { multipart };
});
```

```ts
{
    "multipart": []
}
```

**Comment by becem-gharbi** [comment]
I have figured out the problem behind this. It's related to `readRawBody`. 
On Netlify the `event.node.req.body` is a string encoded in `base64`. When the encoding is falsy, `readRawBody` returns a buffer. The buffer is a created from the body with the default encoding `utf8`. By setting the encoding to `base64` the issue is resolved. 
https://github.com/unjs/h3/blob/12ccb81432a62783fe951a8170976c8162bce44a/src/utils/body.ts#L83

I cannot open a PR for this as I'm not aware of the affected APIs relying on `readRawBody`.

**Comment by becem-gharbi** [comment]
Since this issue depends on the environment, I have moved to nitro https://github.com/unjs/nitro/issues/1719.

**Comment by platform-kit** [comment]
@becem-gharbi sorry to hijack this thread, but I think I may have a similar issue with reading headers via`event.node.req.headers` and the helpers such as `getHeader` when deploying from Nuxt3/Nitro to Netlify. 

Does the discrepancy with `event` on Netlify have anything to do with this?

```
 ERROR  Invoke Error 	{"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'authorization')","stack":["TypeError: Cannot read properties of undefined (reading 'authorization')"," 
```

**Comment by becem-gharbi** [comment]
>@becem-gharbi sorry to hijack this thread, but I think I may have a similar issue with reading headers viaevent.node.req.headers and the helpers such as getHeader when deploying from Nuxt3/Nitro to Netlify.

I don't have such problem with `getHeader` on Netlify, it works well.
