### ISSUE TITLE
What is the difference between `defineEventHandler` and `defineLazyEventHandler`

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/h3#534]
Hello,

I was looking for documentation and I did not understand when I should (could) use the `defineLazyEventHandler`.

**Comment by milos018** [comment]
Hi, recently watched a video on YT by Daniel Route who used it, you can watch at https://youtu.be/P9cP3ZiHe3Q?si=IS_ednGs0s4pGqc2&t=1890 - hope it helps.

**Comment by Barbapapazes** [comment]
Yes, thanks! I also read some code and as I understand, it allows user to configure the `eventHandler` and it return an `eventHandler`.

https://github.com/vercel/ai/blob/5220336b93e2a61e92175a5f7ae81392ed881659/examples/nuxt-openai/server/api/chat.ts#L5
