### ISSUE TITLE
readFormData doesn't work on cloudflare workers (vercel-edge)

### ISSUE THREAD

**Issue by cosbgn** [unjs/h3#538]
### Environment

nuxt 3.7.1

### Reproduction

```
export default defineEventHandler(async (event) => {
	console.log("start 1")
	const form = await readFormData(event)
	console.log("start 2")
})
```

It logs `start 1` and then it hung until it eventually dies with a `502`.

### Describe the bug

When I `await readFormData(event)` it never resolves and eventually it dies with a 502.

### Additional context

Tested on vercel-edge

**Comment by pi0** [comment]
Thanks for making issue. I have managed to make a minimal reproduction with h3 and vercel-edge isolated from nitro (don't ask me how! emulating builder output is a mess..) but anyway it works as expected: https://h3-on-vercel-edge.vercel.app/

This seems a bug originating from how nitro handles request body for vercel edge. So let's keep tracking it there (https://github.com/unjs/nitro/discussions/1718 for reference)
