### ISSUE TITLE
HTTP/1.1 404 Page not found: /status using curl 

### ISSUE THREAD

**Issue by rafaelragib** [unjs/h3#541]
Hello
I have created a server/routes/status for health check in nuxt 3 using the h3. The code is simple:
```typescript
export default eventHandler((event) => {
  setResponseStatus(event, 200);
  return 'ok';
});

``` 
I am trying to run a curl command for this to get the headers.
But I am getting response that is HTTP/1.1 404 Page not found: /status. 
```shell
curl -I -v localhost:3000/status
*   Trying 127.0.0.1:3000...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3000 (#0)
> HEAD /beta/status HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Page not found: /status
HTTP/1.1 404 Page not found: /status
< Access-Control-Allow-Origin: *
Access-Control-Allow-Origin: *
< content-type: application/json
content-type: application/json
< date: Tue, 19 Sep 2023 11:16:50 GMT
date: Tue, 19 Sep 2023 11:16:50 GMT
< connection: close
connection: close

< 
* Closing connection 0

``` 

The response is fine when I am trying to hit the route using the browser. But curl is giving this error. I am not sure why it is happening. Any sort of help will be appreciated.

**Comment by manniL** [comment]
h3 Returns the correct call.

<img width="696" alt="image" src="https://github.com/unjs/h3/assets/640208/32a613b9-a751-4c6a-ac3c-7cdbdbf68166">

You already showed why it broke in your example

[From SO](https://superuser.com/a/272273):
>  NB: curl -I does a HEAD HTTP request, which can be problematic for testing the HTTP status code for some web application servers and services 


So you only configured `GET`, `HEAD` calls will return 404.
If you do a `curl -I -X GET http://localhost:3000/status` (or allow the `HEAD` method too it will succeed.

**Comment by rafaelragib** [comment]
curl -I -X HEAD http://localhost:3000/status

```
HTTP/2 404 
date: Thu, 28 Dec 2023 03:05:42 GMT
content-type: application/json
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-permitted-cross-domain-policies: none
x-xss-protection: 0
access-control-allow-origin: *
```
Not sure if I got you correctly, but I am getting 404 for the curl. It does not succeed

**Comment by manniL** [comment]
@rafaelragib Try `curl -I -X GET http://localhost:3000/status` as I mentioned ☺️

**Comment by rafaelragib** [comment]
@manniL got your point. GET will work. 
We have an alert for health checks that requests only head as we don't need the whole page. This will be a complex work to change the alert.
My concern is shouldn't it work for head/get both as I haven't made the file `get.ts`?

**Comment by manniL** [comment]
@rafaelragib No, because you use `router.get`. You want to use `router.add` and check the method manually then:


```ts
router.add(
  '/',
  eventHandler((event) => {
    if (event.method !== 'GET' && event.method !== 'HEAD') {
      throw createError({ statusCode: 405 });
    }
    return { path: event.path, message: 'Hello World!' };
  })
);
```
