### ISSUE TITLE
bug: different wildcard variables in router breaks routes

### ISSUE THREAD

**Issue by qin-guan** [unjs/h3#543]
### Environment

N/A

### Reproduction

https://github.com/unjs/nitro/issues/1093#issuecomment-1731348886

### Describe the bug

https://github.com/unjs/nitro/issues/1093#issuecomment-1731348886

**Comment by qin-guan** [comment]
This is kind of awkward, seems like it's from radix3 instead of h3

**Comment by qin-guan** [comment]
Upon further investigation, I don't think this is fixable unless h3 is able to pass radix3 some information regarding the HTTP method of the handler. 

For example, on radix3 side, it will have receive routes from h3 along the lines of.

```typescript
const router = createRouter({
  routes: {
    "/nested/:one": { handlers: {} },
    "/nested/:two": { handlers: {} },
  }
})
```

But to radix3, this would not make much sense and would raise ambiguity since both routes are the "same".

**Comment by Hebilicious** [comment]
@qin-guan Could this be fixed with https://github.com/unjs/radix3/pull/59 ?

**Comment by qin-guan** [comment]
Hey @Hebilicious apologies for the late response. Yes I believe it will fix the issue

**Comment by pi0** [comment]
New rewrite of radix3, (rou3) properly matches the corresponding named params (in case that they have different methods). It will be available soon with h3 v2.
