### ISSUE TITLE
Sharing state across a request

### ISSUE THREAD

**Issue by melbourne2991** [unjs/h3#546]
### Describe the feature

> H3 has a concept of composable utilities that accept event (from eventHandler((event) => {})) as their first argument. This has several performance benefits over injecting them to event or app instances in global middleware commonly used in Node.js frameworks, such as Express. 

This is cool, but how can we share state across the lifecycle of a request? 

Given the above I take it we can't (shouldn't) be injecting custom properties on `event`.

Is the event object tied to a single request (and the same object for the duration of the request) ? If yes then we can use a `WeakMap<Event, SomeState>`.
I have a DI container which I want to instantiate only once per request. It's not clear to me how to go about this currently.

Happy to contribute to the docs.

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by danielroe** [comment]
You can do this in `event.context`.

**Comment by pi0** [comment]
Also if you want to persist it across requests, you can use built-in `useSession` util. Let me know if needed any help for implementation.

**Comment by Kilo0110** [comment]
> You can do inject custom properties in `event.context` - it's what it's designed for.

Hi @danielroe I just ran into something similar. I understand you can inject it into `event.context` but how do we access it? Following the Nuxt documentation. server middleware can be used to extend a request before it is being handled. I am trying to utilise that specific behaviour but can't seem to get it to work.

For context (pun unintended), imagine I have a server middleware that injects a custom property called customProperty into the event context like so 

```
event.context.customProperty = value
```

How do I retrieve that customProperty value in my server API route? Trying `event.context.customProperty`  returns `undefined`

**Comment by danielroe** [comment]
Try logging to make sure that middleware is actually running before you try to access the property.

**Comment by Kilo0110** [comment]
Lol, I am going to sound like a total idiot. I was just about to reply that I was logging and the middleware was running but then I decided to take a better look and found out I mistyped in an if condition so the property wasn't been added. The typo was still valid code so it didn't throw any error. Thanks a lot for your reply.
