### ISSUE TITLE
Support optional decoding for `getRouterParam`

### ISSUE THREAD

**Issue by mukundshah** [unjs/h3#547]
### Environment

Node: 18.18.0

### Reproduction

```ts
import { createApp, eventHandler, createRouter } from "h3";

const app = createApp();

const router = createRouter()

router.get(
  '/:name',
  eventHandler((event) => `Hello ${event.context.params.name}!`)
);

app.use(router);
```

### Describe the bug

Expected: **Hello something with test!**
But got: **Hello something%20with%20test!**

param is not being decoded here.

**Comment by pi0** [comment]
Hi and thanks for creating issue. We cannot decode params by default as it can cause to loose information.

Once thing we can do is to support `decode: true` option for `getRouterParam` utility.

**Comment by mukundshah** [comment]
That sounds much better. Shall I send you PR?
