### ISSUE TITLE
[question] File based routes like Nuxt

### ISSUE THREAD

**Issue by angelhdzmultimedia** [unjs/h3#550]
### Describe the feature

Does h3 support file based routes like Nuxt?

```
api/
  auth/
    login.post.ts
```

I wrote a function that does this, but was wondering if h3 comes with this or if we have to implement it.

```ts
app.use(fromNodeMiddleware((req, res) => createRoutes(req, res))
```

Where `createRoutes` does all the file/module loading and http method parsing.

Cheers! 🔥😊🤝☕

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by NozomuIkuta** [comment]
h3 doesn't support filesystem-based routing (at least at the moment).
We have to explicitly tell h3 which route (i.e. path) is associated with which handler (i.e. function) by calling `use` method.

Theoretically, associating URL paths with handlers is a different thing than associating file paths with URL paths.
If you need filesystem-based routing, you might want to use Nitro or check its implementation for reference.

**Comment by angelhdzmultimedia** [comment]
> h3 doesn't support filesystem-based routing (at least at the moment). We have to explicitly tell h3 which route (i.e. path) is associated with which handler (i.e. function) by calling `use` method.
> 
> Theoretically, associating URL paths with handlers is a different thing than associating file paths with URL paths. If you need filesystem-based routing, you might want to use Nitro or check its implementation for reference.

Yeah I was confused as to what was the one I needed, nitro or h3. Thanks for the answer, exactly what I needed https://nitro.unjs.io/guide/routing#specific-request-method! 🔥🤝
