### ISSUE TITLE
How implement Session

### ISSUE THREAD

**Issue by folamy** [unjs/h3#58]
Is there a way to implement session in h3?
```js
req.session => object
```

**Comment by ironytr** [comment]
looking for nuxt3

**Comment by kenta92** [comment]
I need some session store to work with h3.

**Comment by folamy** [comment]
@pi0, well done for you do! 
Is there any update on How to implement server session on h3?

**Comment by wobsoriano** [comment]
In the meantime, you can use this module https://github.com/wobsoriano/h3-session

It's just a wrapper of express-sesssion.

**Comment by wobsoriano** [comment]
In the meantime, you can use this simple module that wraps express-session

https://github.com/wobsoriano/h3-session

**Comment by pi0** [comment]
Session support just landed via https://github.com/unjs/h3/pull/315. Feedbacks more than welcome.
