### ISSUE TITLE
Custom event class

### ISSUE THREAD

**Issue by HigherOrderLogic** [unjs/h3#580]
### Describe the feature

I notice that some functions (not all) have event type generic.

https://github.com/unjs/h3/blob/09b49d5cd521bb715023ae903ded8a98cdbf65ac/src/utils/request.ts#L13-L17

https://github.com/unjs/h3/blob/09b49d5cd521bb715023ae903ded8a98cdbf65ac/src/utils/request.ts#L21-L25

So is it possible for user to use their own custom event class provided to `createApp`? 

Example: 

```ts
class MyEvent extends H3Event { ... }

const app = createApp({ eventClass: MyEvent })
```

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi @HigherOrderLogic. Generic is to augment types of event. App/Adapter itself constructs the event class
