### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by agracia-foticos** [unjs/h3#583]
### Environment

- Operating System: `Linux`
- Node Version:     `v20.5.1`
- Nuxt Version:     `3.8.2`
- CLI Version:      `3.10.0`
- Nitro Version:    `2.8.0`
- Package Manager:  `npm@9.8.0`
- Builder:          `-`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

![image](https://github.com/unjs/h3/assets/77386602/8429506a-1c76-478b-9ff0-e0db10abb600)

### Describe the bug

![image](https://github.com/unjs/h3/assets/77386602/52c2ec09-c655-467b-a245-babb4b41e1f7)

**Comment by danielroe** [comment]
would you provide a reproduction? 🙏

**Comment by agracia-foticos** [comment]
> would you provide a reproduction? 🙏

We have a lot of code generated, it is impossible to have a minimal playback environment

**Comment by pi0** [comment]
Sadly nothing we can to check without reproduction. Issue might be possibly from any of the higher level stack in nitro, nuxt, your used nuxt modules or application logic itself.
