### ISSUE TITLE
How to return streaming data from h3 api

### ISSUE THREAD

**Issue by prashantnirgun** [unjs/h3#584]
I am trying to create PDF at server side which is in server/api/member I am using PDFMake using some custom Unicode font.  I am converting data into base-64 but not understand how return it. I still don't understand do I really need a call back ?
Got stuck in between. If I provide fs object to pdfDoc.pipe() then PDF file get created and saved to server but again that is lengthy process. I just need PDF should get downloaded.

Its not a bug, just missing example for download file. I am new to H3 please help 
```
import pdfPrinter from "pdfmake";
import { Base64Encode } from "base64-stream";
async function createPDF(cb) {
    const docDefinition = {
      content: [
        "Report",
        "This is an sample PDF printed with",
      ],
     
    };

    const printer = new pdfPrinter();
    const pdfDoc = await printer.createPdfKitDocument(docDefinitions);
    const stream = await pdfDoc.pipe(new Base64Encode());
    pdfDoc.end();
  
    let finalString = "";
    stream.on("data", function (chunk) {
      finalString += chunk;
    });
    stream.on("end", function () {
      return cb("data:application/pdf;base64," + finalString);
    });
}
export function createReceipt() {
  return async (event) => {
    try {
      const response = await createPDF((response) => {
        return response;
      });
}
```
No data is returned.

**Comment by joshmossas** [comment]
I'm not familiar with either of the libraries you are using but the way you stream data with H3 is by using the `sendStream` utility.

For example let's assume I want to stream a large file in NodeJS. I would simply do this:

```ts
defineEventHandler((event) => {
  const stream = createReadStream("/path-to-some-file.pdf");
  await sendStream(event, stream);
});
```

So in your case you would take a ReadableStream generated by the library you are using and just pass it to the `sendStream` utility.

**Comment by pi0** [comment]
Equality you could just `return stream` h3 should handle it nicely cross-platform and will internally use `sendStream`.

If you still had issue, please make a github repository and ping me to check 👍🏼

**Comment by prashantnirgun** [comment]
I tried a lot but didn't work can any one fix this will be a great help. I tested the base64 value with online decoder it generate pdf that means till that part is ok. Only thing return the PDF without saving it on server.

I believe the buffer should return data as on when received or hold till last chunk and send it ? I checked sendStream() and return both didn't work out.

```
export function createStreamFile() {
  return async (event) => {
    try {
      var fonts = {
        Poppins: {
          normal: path.join(
            process.cwd(),
            "server/hmvc/members/fonts/Poppins/Poppins-Regular.ttf"
          ),
        },
      };

      const docDefinition = {
        content: [
          "प्रशांत रमेश निर्गुण",
          "This is an sample PDF printed with स्वरा",
        ],
        defaultStyle: {
          font: "Poppins",
        },
      };

      const printer = new pdfPrinter(fonts);
      const options = {};
      let chunks = [];
      let result;
      const pdfDoc = printer.createPdfKitDocument(docDefinition, options);

      pdfDoc.on("data", (chunk) => {
        chunks.push(chunk);
      });

      pdfDoc.on("end", () => {
        result = Buffer.concat(chunks);
        /* output of result
        <Buffer 25 50 44 46 2d 31 2e 33 0a 25 ff ff ff ff 0a 38 20 30 20 6f 62 6a 0a 3c 3c 0a 2f 54 79 70
        */
        const pdfdata = "data:application/pdf;base64," + result.toString("base64");
          /* output of pdfdata 
          data:application/pdf;base64,JVBERi0xLjMKJf////8KOCAwIG9iago8PAovVHlwZSAvRXh0R1N0YXRlCi9jYSAxCi9DQSAxC
          */
        
        //sendStream(event, pdfdata);
        return pdfdata;
      });

      pdfDoc.end();

    } catch (error) {
      console.log("error", error);
      return error;
    }
  };
}```
