### ISSUE TITLE
When I request a non-existent API address, I cannot return 404 normally, but instead return 204

### ISSUE THREAD

**Issue by wangweiji1006** [unjs/h3#597]
### Environment

node.js version v18.18.0

### Reproduction

1.When I use/server/API/dict/[...slug]. ts to define an API, it looks like this:
![image](https://github.com/unjs/h3/assets/19835678/18a50670-db13-448e-9153-8cb9417bd802)
/server/api/dict/[..slug].ts code：
import Joi from "joi";
import { plainToInstance } from "class-transformer";
import { HError } from "~/server/action/HError";
import { Dict } from "~/server/entity/Dict";
import { AbsEntity } from "~/server/entity/AbsEntity";
import { sleep } from "~/server/action/Test";
const router = createRouter();

router.post(
  "/page",
  defineEventHandler(async (event) => {
    const { page, pageSize, orderBy, query } = await readBody(event);
    const queryBuilder = Dict.createQueryBuilder().orderBy(orderBy);
    if (query.groupId) {
      queryBuilder.where("groupId = :groupId", query);
    }
    const data = await AbsEntity.paginate<Dict>(page, pageSize, queryBuilder);
    return data;
  }),
);
router.post(
  "/delete",
  defineEventHandler(async (event) => {
    const body = await readBody(event);
    await Dict.delete({ id: body.ids });
    return "ok";
  }),
);
router.post(
  "/save",
  defineEventHandler(async (event) => {
    const body = await readBody(event);
    const schema = Joi.object({
      id: Joi.string(),
      name: Joi.string().max(10).required().messages({
        "string.base": "请输入字典名称",
        "string.empty": "请输入字典名称",
        "string.max": "字典名称不允许超过10个字符",
      }),
      key: Joi.string().max(10).required().messages({
        "string.base": "请输入字典标识",
        "string.empty": "请输入字典标识",
        "string.max": "字典标识不允许超过10个字符",
      }),
      groupId: Joi.string().required().messages({
        "string.base": "请选择字典模块",
        "string.empty": "请选择字典模块",
      }),
      values: Joi.array(),
    });
    const valid = schema.validate(body);
    HError.validJoi(valid.error);
    const data = plainToInstance(Dict, body);
    await data.save();
    await sleep(2000);
    return "ok";
  }),
);
export default useBase("/api/dict", router.handler);
2.When I directly access a non-existent API address in a browser, such as http://localhost:3000/api/dict/getbyid?id=1 perhaps http://localhost:3000/api/dict/test Wait, the status codes returned by the interface are all 204, and I don't want that to happen. I hope to return 404, how should I modify it?

Tested access http://localhost:3000/api/dict2/getbyid?id=1 When it comes to [.. Slug]. ts, it does indeed return a 404 error. I think it's because [.. Slug]. ts did some internal processing.

### Describe the bug

I hope to use [...slug]. ts to define multiple APIs within a module, and access non-existent addresses can return 404

**Comment by manniL** [comment]
You'd manually set the status code to `404` *or* throw a 404 error, e.g. via `createError`.
