### ISSUE TITLE
Overwriting headers Set-Cookie

### ISSUE THREAD

**Issue by Pinegin** [unjs/h3#598]
### Environment

node: 20.8.1
h3: 1.9.0

### Reproduction

await deleteCookie(event, 'test', { domain: example.test })
await deleteCookie(event, 'test', { domain: .example.test })

### Describe the bug

It is impossible to delete cookies using the "deleteCookie" method, cookies of the same type but with different parameters

https://github.com/unjs/h3/blob/main/src/utils/cookie.ts#L54-L56

**Comment by unite4** [comment]
+1
