### ISSUE TITLE
Default content-type `text/html` used in 304 responses of static assets

### ISSUE THREAD

**Issue by grob** [unjs/h3#603]
### Environment

Node 18, Nuxt 3.8.2, Nitro 2.8.1

### Reproduction

none

### Describe the bug

Ran into this issue using Nuxt in production mode and a static `.svg` asset.

H3 uses the default content-type `text/html` for 304 responses. Apparently this happens in [handleHandlerResponse](https://github.com/unjs/h3/blob/53703dc860f1ff6fe7ce71d543deff1cfa810b11/src/app.ts#L255) - 304 responses have an empty string body, and the function [defaultContentType](https://github.com/unjs/h3/blob/53703dc860f1ff6fe7ce71d543deff1cfa810b11/src/utils/response.ts#L78) called subsequently only checks if the `content-type` header has been set already, but **not** if the response code is 304. Thus the default content type `text/html` is applied.

[RFC 7232 suggests](https://www.rfc-editor.org/rfc/rfc7232#section-4.1) that 304 responses should not contain a `content-type` header, so i think checking the response code too in `defaultContentType()` should be sufficient (although i'm not sure if this would be the right spot to change).

See also https://github.com/unjs/nitro/issues/1700

**Comment by Jamie4224** [comment]
@grob It already wreaks havoc when Nuxt is used in conjunction with Google Cloud CDN, sadly enough. Cloud CDN picks up the text/html content-type on a cache validation call. After that browsers block these static assets from loading since strict mime checks fail.

**Comment by botic** [comment]
Same behind a Varnish. And it prevents using a CSP security policy for assets, so this could be labeled as minor security issue as well.

**Comment by grob** [comment]
@Jamie4224 did you find a workaround (or temporary fix)? we're currently re-applying the content-type of the stale (= cached) version in varnish for 304 responses from nuxt …

**Comment by Jamie4224** [comment]
@grob No, our workaround was disabling Cloud CDN for the moment. The only other workaround I see is forcefully applying a content-type based on the extension (probably what you are doing?).

**Comment by grob** [comment]
Unfortunately i have no experience with cloud cdn - as i said, we're currently using the content-type of the cached (http 200) version of a response whenever the backend (= nuxt) returns a 304. sadly enough, that's the only way we could fix it, but fortunately varnish allows to do that. still it's pretty disappointing.

**Comment by pi0** [comment]
The fix will be landed in next patch. Thanks for reporting.

**Comment by Jamie4224** [comment]
Much appreciated, thanks!
