### ISSUE TITLE
Concurrent calls to `getSession` leads to only the first one getting the session

### ISSUE THREAD

**Issue by edivados** [unjs/h3#610]
### Environment

stackblitz
h3: 1.10.0
node: 18.18

### Reproduction

Barebone reproduction using `H3Event` and `useSession` only.
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/stackblitz-starters-jyfqat?file=index.js)

Solid-Start repro by the issue author here https://github.com/solidjs/solid-start/issues/1192
[![Open in StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/metruzanca-solidstart-getsession-bug-repro-xd4fmg?file=README.md)

Steps (for Solid-Start Repro):

1. Press Login button
2. Refresh page - You are logged out
3. Press Index link - You are logged in

### Describe the bug

When calling `getSession` multiple times concurrently on a single page request the first call will initialize the `context.sessions[sessionName]` to an empty session. All other calls will see that there is a session on the context and return it.

### Additional context

I guess `unsealSession` gives the other calls a chance to advance to the context check and return early.
If appropriate the session assignment to the context could be done after `unsealSession`. While testing it helped but this would lead to the session being unseald multiple times.
https://github.com/unjs/h3/blob/ae91fc8658315dca75da22b665eda4175eef7ea8/src/utils/session.ts#L108

**Comment by JAD3N** [comment]
Changing the session assignment to after seems like it could cause issues. I submitted a PR that will block `getSession` when waiting for a pending unseal.

**Comment by edivados** [comment]
Using a lock sounds good. Thank you.

**Comment by pi0** [comment]
Thanks for the nice reproduction @edivados ❤️
