### ISSUE TITLE
using request body from `getRequestWebStream` stalls with Nitro's Deno Deploy/Vercel Edge runtime

### ISSUE THREAD

**Issue by oscartbeaumont** [unjs/h3#615]
### Environment

```
➜ deno --version
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2

➜ node --version
v20.7.0

➜ pnpm -v
8.14.1
```

### Reproduction

https://github.com/oscartbeaumont/h3-nitro-body-bug

### Describe the bug

Nitro's Deno + Vercel Edge Functions adapters pass an `ArrayBuffer` in as the body of the request ([ref](https://github.com/unjs/nitro/blob/0473241c138ab625ba13d8152e70d6ad3c6803c7/src/runtime/entries/deno-deploy.ts#L37)).

When a downstream package (in my case [Vinxi](https://github.com/nksaraf/vinxi) on behalf of [Solid Start](https://github.com/solidjs/solid-start)) calls [`getRequestWebStream`](https://github.com/unjs/h3/blob/845eecaaaeffdb415321f76744e31d55074f37b8/src/utils/body.ts#L253) the `ReadableStream` that comes back never resolves.

This causes `request.json()`, `request.text()` and `request.arrayBuffer()` to stall.

Following along with the implementation of the H3's [`getRequestWebStream`](https://github.com/unjs/h3/blob/845eecaaaeffdb415321f76744e31d55074f37b8/src/utils/body.ts#L253). function:

`event.web?.request?.body` is `undefined` so we go to the next condition,
`event._requestBody` is `undefined` so we go to the next condition,
We reach the "finally" condition and create a `ReadableStream` and call `event.node.req.on` to set up listeners to the body.

However, none of the `.on(...)` callbacks fire when the `body` is an `ArrayBuffer` so the promise hangs and the entire function freezes.

### Additional context

Related to:
 - https://github.com/solidjs/solid-start/pull/1255
 - https://github.com/nksaraf/vinxi/pull/123

**Comment by pi0** [comment]
Thanks for reproduction and explanations ❤️ Issue should be solved in h3-edge channel and soon in h3 stable.
