### ISSUE TITLE
Incompatible streams with raw values from unstorage when used in `sendStream`

### ISSUE THREAD

**Issue by GalacticHypernova** [unjs/h3#623]
### Environment

N/A

### Reproduction

https://github.com/GalacticHypernova/NuxtFailTest

Steps:
1. npm install
2. npm run dev
3. navigate to localhost:3000/images/Test2.jpg
4. profit

### Describe the bug

When sending streams of images using sendStream, it complains that the stream of the item is not compatible. That is beause, from what I understood, it takes the raw file content which is a buffer of bytes, and the sendStream function expects an object with `pipe` or `pipeTo` properties.

### Additional context

This doesn't occur when using `createReadStream` from `node:fs`

**Comment by pi0** [comment]
You should call `createReadStream` with stream values only. One better way is to always use `return <value>` and let h3 dispatch to the right method.
