### ISSUE TITLE
Remove warning for `defineEventHandler`

### ISSUE THREAD

**Issue by pi0** [unjs/h3#643]
For historical reasons, we were used to automatically convert legacy express middleware to h3 handlers and when we changed that, we started to [add a warning](https://github.com/unjs/h3/blob/da128d8c2f8190eb0cb9b8310fe12ee090f9a81d/src/event/utils.ts#L118).

Most of the advanced features of h3 including type inference, object syntax, and middleware are only possible with this wrapper only and i think we probably always advice for it in all docs too.

But.. it often causes DX issues when we want simply draft a handler (`app.use(() => 'ok')`) or try something or make an internal utility that is already typed.

I am thinking to remove the warning (while keep always using in docs). 

/cc @danielroe do you have any concerns specifically re legacy reasons to keep?

**Comment by danielroe** [comment]
I agree 👌
