### ISSUE TITLE
proxyRequest() is unable to handle DELETE requests with undefined body

### ISSUE THREAD

**Issue by giftimie** [unjs/h3#645]
### Environment

H3 1.10.1
Node 20.10.0

### Reproduction

In one of my own Nuxt projects I am using H3 as a proxy to my backend. My backend accepts DELETE requests with no body required.

If I do not specify a body, H3Event has an undefined body, as expected. However, after calling proxyRequest(), the following is logged.
In the console:
```
[nuxt] [request error] [unhandled] [500] fetch failed
  at Object.fetch (node:internal/deps/undici/undici:11730:11)
  at async sendProxy (/C:/Users/user/<project-path>/node_modules/h3/dist/index.mjs:1096:20)
  at async Object.handler (/C:/Users/user/<project-path>/node_modules/h3/dist/index.mjs:1697:19)
  at async Server.toNodeHandle (/C:/Users/user/<project-path>/node_modules/h3/dist/index.mjs:1907:7)
```

As the response to the request:

```
{
	"url": "/api/posts/1",
	"statusCode": 500,
	"statusMessage": "",
	"message": "fetch failed",
	"stack": "<pre><span class=\"stack internal\">at Object.fetch (node:internal/deps/undici/undici:11730:11)</span>\n<span class=\"stack internal\">at async sendProxy (/C:/Users/user/<project-path>/node_modules/h3/dist/index.mjs:1096:20)</span>\n<span class=\"stack internal\">at async Object.handler (/C:/Users/user/<project-path>/node_modules/h3/dist/index.mjs:1697:19)</span>\n<span class=\"stack internal\">at async Server.toNodeHandle (/C:/Users/user/<project-path>/node_modules/h3/dist/index.mjs:1907:7)</span></pre>"
}
```

However, if I do specify a body, such as `{}`, the request goes through with no issues.

This does not happen with POST requests.

Minimal reproduction: https://stackblitz.com/edit/nuxt-ui-6zmvwx?file=server%2Fapi%2F%5B...%5D.ts 

### Describe the bug

proxyRequest should forward the request to the backend even with an undefined body, however an error is thrown and the request does not reach the backend.

On the other hand, a POST request with an undefined body does go through as expected and it reaches the backend.

**Comment by Barbapapazes** [comment]
Hello, 

related to #375
related to #605

This come from a bug in Unidici: https://github.com/nodejs/undici/issues/2046.

**Comment by calebwaldner** [comment]
I had the same issue using `proxyRequest` with a DELETE request and empty body. After some research, I found it seemed to be related node. Updated my node version to `v20.14.0` and all works great now 👍🏼

**Comment by Shawyeok** [comment]
Same issue here. Upgrading Node.js to `v18.20.7` from `v18.17.0` fixed it.
