### ISSUE TITLE
Top level `event` should not be assigned with new props

### ISSUE THREAD

**Issue by pi0** [unjs/h3#647]
Context: saw an instance from https://github.com/nuxt/nuxt/issues/25442#issuecomment-1911997902 but also previously in some other codebases

The `event: H3Event` is a class but it is not immediately obvious in usage. Allows to override its top-level props which can lead to conflicting situations. Only `event.context` is the user context to be modified.

To avoid bigger issues for this usage and inform users ahead of time I am thinking of a two-stage process:
- 1. Use a proxy that warns users and stores in an alternative place to avoid immediate breaking change
- 2. Disallow the property assignment after a while 

(on a related topic, we also should probably make sure `event` is not restructured as an ES6 object. i saw it even in some official examples!)

**Comment by CHIBX** [comment]
> Context: saw an instance from [nuxt/nuxt#25442 (comment)](https://github.com/nuxt/nuxt/issues/25442#issuecomment-1911997902) but also previously in some other codebases
> 
> The `event: H3Event` is a class but it is not immediately obvious in usage. Allows to override its top-level props which can lead to conflicting situations. Only `event.context` is the user context to be modified.
> 
> To avoid bigger issues for this usage and inform users ahead of time I am thinking of a two-stage process:
> 
>     * 1. Use a proxy that warns users and stores in an alternative place to avoid immediate breaking change
> 
>     * 2. Disallow the property assignment after a while
> 
> 
> (on a related topic, we also should probably make sure `event` is not restructured as an ES6 object. i saw it even in some official examples!)

Maybe you could combine the issues that could cause breaking changes, and then push a fix with the changes in a new version in the later future. However, I do agree that the event params should not allow assignment of props, and only event.context should.

**Comment by pi0** [comment]
Sadly it cannot happen without adding perf overhead, we might only hope via docs that people won't do this.
