### ISSUE TITLE
Chunk large session cookies

### ISSUE THREAD

**Issue by RihanArfan** [unjs/h3#649]
### Describe the feature

When trying to set a session with data that exceeds 4096 characters, a cookie isn't created. To support session data with more than 4096 bytes, next-auth and dotnet chunk their cookies.

I'm trying to store a JWT access and refresh token within the session, and the JWT from my OAuth2 provider (Microsoft Entra ID) is rather large.

I'm using Atinux's nuxt-auth-utils library, however, it doesn't do anything special on top of h3's session which is why I'm reporting here. https://github.com/Atinux/nuxt-auth-utils/blob/main/src/runtime/server/utils/session.ts#L31-L37

- https://stackoverflow.com/questions/60649050/javascript-set-cookie-max-size-is-exceeded-due-to-a-large-jwt-token
- https://www.cyberchief.ai/2023/05/secure-jwt-token-storage.html
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.authentication.cookies.chunkingcookiemanager

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by DylanThomasFr** [comment]
I support this. The limit is reached really fast.

**Comment by pi0** [comment]
This is nothing h3 can do, you (and libraries) should assume HTTP headers limitation and store only essential state in cookie and load the rest from a database or external storage.

**Comment by Siilwyn** [comment]
Just got bitten by this, though I agree with the sentiment that limits should be respected it seems h3 could help out with a functions like `getCookieAll` & `setCookieAll` that work with chunked cookies.

**Comment by tschni** [comment]
@RihanArfan @Siilwyn I am currently facing exactly the same problem with my project. How were you able to solve it?

**Comment by Siilwyn** [comment]
Hi @tschni ended up following [Lucia's guide](https://lucia-auth.com/) to auth.
