### ISSUE TITLE
tsconfig.json error Cannot write file '/api/inventories/[...].js' because it would overwrite input file.

### ISSUE THREAD

**Issue by prashantnirgun** [unjs/h3#654]
I am using JS and not TS and my VSCode showing me 57 Problems. Any one know how do I fix this? I really now used TypeScript so may be I am breaking any linting error. Its not stopping me but some other day I keep it open for long time. Content of my tsconfig.json is as follows.
```
{
  "extends": "./.nitro/types/tsconfig.json"
}
```
Thanks in advance

**Comment by pi0** [comment]
This issue should be fixed in next version of Nitro but if happens, you might need to set `compilerOptions: { "noEmit": false }` in `tsconfig.json` file
