### ISSUE TITLE
Opt-out of preemptive mode per handler

### ISSUE THREAD

**Issue by manniL** [unjs/h3#656]
### Describe the feature

After https://github.com/unjs/h3/pull/409 was merged, a big DX issue was resolved.
In some situations, it would be helpful to purposefully achieve the same behavior: Letting the app match other handlers (see https://github.com/nuxt/nuxt/issues/25885).

It would be great to have a way to opt-out of the preemptive mode for a handler!

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I love to help to find a better solution for cases like the ones in https://github.com/nuxt/nuxt/issues/25885 to avoid using middleware pattern and alternatively use composable utils. 

Generally I think preemptive should be always default behavior and utils prefers so it is probably not something consistent with the roadmap.

Let's track via downstream issue first & I would be happy to rediscuss if there are common enough usecases we are thinking that this can help.

**Comment by pi0** [comment]
(update: with https://github.com/unjs/h3/pull/822 and h3 v2, legacy middleware with `.use` are non-preemptive  and route handler with `.get`, or `.add` or `.all` will be preemptive) [wip]
