### ISSUE TITLE
Use either of `eventHandler` and `defineEventHandler` consistently in documentation

### ISSUE THREAD

**Issue by NozomuIkuta** [unjs/h3#664]
### Describe the change

It is said in [event-handler page](https://h3.unjs.io/guide/event-handler) that, 

>  You can use `eventHandler` and `defineEventHandler` interchangeably. They are aliases. You can use the one you prefer but stick to it for consistency.

In this point, h3 docs doesn't stick to either of them.
Although documentation and its sample code are not actual application code, 
it might be better to follow the convention that it tells by itself.

If @pi0 and/or @Barbapapazes tell me which to go, I will submit a PR to unify usages, 
or please close this issue if it's fine to use both for some reasons.

### URLs

All pages where `eventHandler` and `defineEventHandler` are used.

### Additional information

- [X] Would you be willing to help?

**Comment by Barbapapazes** [comment]
You are right! 😄

You can update `eventHandler` to `defineEventHandler` which is I think the most used in the docs!
