### ISSUE TITLE
Use `proxyRequest` without rewriting the URL / path.

### ISSUE THREAD

**Issue by scripness** [unjs/h3#686]
Hi! Is it possible to use `proxyRequest` or `sendProxy` without rewriting the path?

Note: this is used in a server middleware within Nuxt.

**Comment by pi0** [comment]
You can pass event.path as second argument to `proxyRequest` like `proxyRequest(event, new URL(event.path, "https://proxy"))` to pass the incoming request's path to the proxy backend
