### ISSUE TITLE
Improve formatEventStreamMessages function

### ISSUE THREAD

**Issue by tmohammad78** [unjs/h3#689]
### Describe the feature

Hi
Whats your opinion to use ```Reduce``` function in [this](https://github.com/unjs/h3/blob/27f6fad97dd0292d82fe30d9a7f4fca7511763ea/src/utils/sse/utils.ts#L26) function

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
https://github.com/unjs/h3/pull/690#issuecomment-2061368708
