### ISSUE TITLE
Improve route matching (raw) performance

### ISSUE THREAD

**Issue by redbar0n** [unjs/h3#692]
### Describe the feature

Hono uses a [faster](https://hono.dev/concepts/routers) [RegExpRouter](https://hono.dev/concepts/routers#regexprouter) instead of a [Radix Tree](https://en.wikipedia.org/wiki/Radix_tree) based router such as [Radix3](https://github.com/unjs/radix3) which H3 currently uses.

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
I appreciate your concern about performance and suggestions. 

I invite you to check the [radix3 benchmarks](https://github.com/unjs/radix3/tree/main/benchmark) and see if the raw matcher responsiveness of 7M ops is less than of your real world usage expectations that might need an alternative method.

There is also an off-topic discussion in https://github.com/unjs/radix3/issues/58 which I will respond in the future.

---

Generally regarding performances please consider the main bottleneck in any real world server application is _not_ the core or route matcher but user logic and the composition of utilities in which h3 tries to best at. 

We can make small adjustments to radix3 to increase benchmark results for specific route conditions but it is just much lower priority comparing to priorities such as ecosystem compatibility.

**Comment by pi0** [comment]
Also made https://github.com/unjs/radix3/issues/85 as tracker let's move discussion there. 

(if you still believe there are strong reasons h3 usage would significantly be different by opting to a different router, we can definitely come back to this 👍🏼 )

**Comment by aquapi** [comment]
@redbar0n @pi0 you may see hono regex router being faster as the router doesn't parse the params into an object but instead keep it in an array which it can be obtained later by prototype pollution.(c.req.param)

**Comment by aquapi** [comment]
But @medley/router algorithm is still the fastest as of rn
