### ISSUE TITLE
Merge set cookie value for same name multiple times

### ISSUE THREAD

**Issue by arily** [unjs/h3#705]
### Environment

Nuxt 3.10.3 with Nitro 2.9.1
Node 20.10.0

### Reproduction

```js
setCookie(e, 'session', '123', { httpOnly: true })
// ...
setCookie(e, 'session', '123', { httpOnly: true, maxAge: /* 1m */ 60 * 60 * 24 * 30 })
```

### Describe the bug

will actually set cookie twice:
```http
set-cookie: session=123; Path=/; HttpOnly
set-cookie: session=123; Max-Age=2592000; Path=/; HttpOnly
```

**Comment by pi0** [comment]
Hi dear @arily. Cookies with different name, domain, path, secure, httpOnly or sameSite props, are technically unique ones. 

maxAge should not made different behavior and this issue will be fixed in upcoming h3 v2.

**Comment by pi0** [comment]
Issues with merging cookies will be solved in upcoming h3 v2
