### ISSUE TITLE
Add getRequestOrigin(event)

### ISSUE THREAD

**Issue by DavidDeSloovere** [unjs/h3#713]
### Describe the feature

A new `getRequestOrigin(event)` util would be useful.
It's a combination of `getRequestProtocol(event) + '://' + getRequestHost(event)`.

Shall I send a PR?

### Additional information

- [X] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
Hi. You can use `getRequestURL(event).origin` 

(please ping me to reopen if I didn't understand correctly)
