### ISSUE TITLE
Mount websocket on same path as another handler

### ISSUE THREAD

**Issue by tobiasdiez** [unjs/h3#719]
### Environment

Nightly version of h3

### Reproduction

Is there a template to start a reproduction?

### Describe the bug

If you have a websocket handler and a normal handler on the same route, say
```
app.use('/', [
  defineWebSocketHandler({...}),
  defineEventHandler({...}),
])
```
or, the other way around,
```
app.use('/', [
  defineEventHandler({...}),
  defineWebSocketHandler({...}),
])
```
Then only the websocket or the normal request is working (depending on which comes first).

**Comment by pi0** [comment]
This is how internally `defineWebSocketHandler` is implemented:

```js
export function defineWebSocketHandler(hooks: Partial<WSHooks>) {
  return defineEventHandler({
    handler() {
      throw createError({
        statusCode: 426,
        statusMessage: "Upgrade Required",
      });
    },
    websocket: hooks,
  });
}
```

As you can see, it is a shortcut wrapper. You can directly use object syntax to mix:

```js
  return defineEventHandler({
    websocket: hooks,
    handler() {
      // Your logic
    },
  });
```

**Comment by tobiasdiez** [comment]
Thanks, this seems to work well on non-root paths but the websocket listeners are not invoked when I use the root path (`app.use('/', ...`).

Is this a known bug or should I open a new report?
