### ISSUE TITLE
`EventStream` convert `'\n'` to `''`

### ISSUE THREAD

**Issue by gyhyfj** [unjs/h3#733]
### Environment

node 20.12.1
nitropack 2.9.6

### Reproduction

// server side
const eventStream = createEventStream(event)
eventStream.push('\n')

// client side
const sse = new EventSource('path/to/sse')
sse.addEventListener('message', e => {
    console.log(e.data'')
})

### Describe the bug

hope to deliver `'\n'` to client side, but get `''`

**Comment by joshmossas** [comment]
Server sent event messages are delimited by `\n\n`. So if you send a message that is only a single newline the client will see ```data:\n\n\n``` and think that the message has ended after the second newline.

So if you want to send a single newline as a message you will probably need to escape it.
