### ISSUE TITLE
`message` field in `createError` not included in response

### ISSUE THREAD

**Issue by siranweb** [unjs/h3#757]
### Environment

node: 20.11.1
h3: 1.11.1

### Reproduction

https://stackblitz.com/edit/github-d9z5tl-zkmmw7?file=app.ts

### Describe the bug

Regarding [docs](https://h3.unjs.io/guide/event-handler#error-handling), I expect to see `message` field in response when it passed to `createError`. Not sure, is it actually a bug or a docs issue

### Additional context

I checked [error.ts](https://github.com/unjs/h3/blob/58e33ff00b1db1cf86a780bf8b152c3f7e573350/src/error.ts#L109). Seems like `message` field insn't being used in response at all. Maybe it was expected to work like `status`/`statusCode`, when one of fields appears in response as `statusCode`

**Comment by pi0** [comment]
Hi dear @siranweb. You should use `data` field if want to transfer some data into client-side. message won't be transferred. (docs is also updated with notice)
