### ISSUE TITLE
how to use match option in h3

### ISSUE THREAD

**Issue by 1018715564** [unjs/h3#76]
In my program, there are nested routes, such as `/api/a `and `/api/a/detail`, but due to fast prefix matching, when I access `/api/a/detail`, the trigger is still `/api/a'`s callback function, what should I do now?

**Comment by 1018715564** [comment]
@pi0

**Comment by pi0** [comment]
Hi @1018715564. Have you tried new router: https://github.com/unjs/h3#router 

It will properly sort routes and match with exact pattern first.

Please let me know if need any help regarding this and reopening issue. Cheers!

**Comment by pi0** [comment]
That's definitely an issue! Moved it to #77 and solve
