### ISSUE TITLE
String vs object errors with `createError` and accessing server-thrown errors on client

### ISSUE THREAD

**Issue by ymansurozer** [unjs/h3#761]
### Describe the change

I have always been somewhat confused on how to initialize `createError`, either with a string or an object. Similarly, it was unclear at first which one to use to pass data to the client in an error thrown from the server.

It would be good to add a section to Guide > Event Handler > Error Handling to make these clear especially for newcomers. Also per @pi0's recommendation, we can extend the jsdoc comment of the `createError` utility to include a short description on the same.

### URLs

https://h3.unjs.io/guide/event-handler#error-handling

### Additional information

- [X] Would you be willing to help?

**Comment by pi0** [comment]
Thanks for the docs. We should improve API too!
