### ISSUE TITLE
router issue with query params

### ISSUE THREAD

**Issue by pi0** [unjs/h3#77]
@pi0 Hello, Thank you very much `createRouter` for solving my problem. I used the add function to successfully add a route for a get request, and it works normally, but if I add a query parameter after the URL, such as `/a?title=a`, Such a route will fail to match;

_Originally posted by @1018715564 in https://github.com/unjs/h3/issues/76#issuecomment-1080773373_

**Comment by 1018715564** [comment]
@pi0

**Comment by pi0** [comment]
Solved by #78
