### ISSUE TITLE
Performance is horrible

### ISSUE THREAD

**Issue by huseeiin** [unjs/h3#798]
### Describe the feature

After testing with Bun.serve() and h3:

"Hello World"
h3: 10k req/s
Bun.serve: 50k req/s

### Additional information

- [ ] Would you be willing to help implement this feature?

**Comment by pi0** [comment]
h3 was designed for Node.js environments (and super fast for node). H3 v2 is based on web API now and it is almost close to native perf. check main branch `bun bench:bun`

<img width="599" alt="image" src="https://github.com/user-attachments/assets/6210f882-41f8-407a-b762-af83620e9a12">

**Comment by huseeiin** [comment]
> h3 was designed for Node.js environments (and super fast for node). H3 v2 is based on web API now and it is almost close to native perf. check main branch `bun bench:bun`
> <img alt="image" width="599" src="https://private-user-images.githubusercontent.com/5158436/350126923-6210f882-41f8-407a-b762-af83620e9a12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4MzU0MjQsIm5iZiI6MTcyNDgzNTEyNCwicGF0aCI6Ii81MTU4NDM2LzM1MDEyNjkyMy02MjEwZjg4Mi00MWY4LTQwN2EtYjc2Mi1hZjgzNjIwZTlhMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMDg1MjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUwZjQwMDA0MTEzMTY1MjMzN2RkYjk4OWU4NWFiYjY3ODEwZjAwMmU3ZmQ0N2Y4NzQ3ODA0ZmNiMWVlMGJiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ePs9meioD5n7Sx21NzQaRrExQBbhnwfVT-EBeajG20s">

does that mean its no longer gonna generate IncomingMessage and ServerResponse for none-node environments like Bun, Cloudflare, Deno, etc.?
