### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by carcinocron** [unjs/h3#82]

**Comment by m0ksem** [comment]
@pi0. Do you want to work on it? I could make a PR for CORS support.

**Comment by NozomuIkuta** [comment]
For your reference, I'm creating [h3-native CORS event handler](https://github.com/NozomuIkuta/h3-cors), whose APIs are mostly same as [Express CORS middleware](https://github.com/expressjs/cors).

README is not yet written, but I believe the code is so simple that you can understand what API looks like.

I've implemented basic features and unit tests, and now I need a kind of e2e tests to test CORS works as expected.
Any advice or feedback is welcome.

**Comment by NozomuIkuta** [comment]
> For your reference, I'm creating [h3-native CORS event handler](https://github.com/NozomuIkuta/h3-cors), whose APIs are mostly same as [Express CORS middleware](https://github.com/expressjs/cors).

I published it to npm with additional unit tests and README.

https://www.npmjs.com/package/@nozomuikuta/h3-cors

---

By the way, this is my first experience of using [unjs/template](https://github.com/unjs/template).
I found some points to improve, so I will create issues and submit PRs later.

**Comment by NozomuIkuta** [comment]
@pi0 
By the way, may I add my package above to Add-on section in README?

**Comment by pi0** [comment]
I think we shall still add cors utility to the h3 main utils.
