### ISSUE TITLE
useQuery(req)  return all DOM page.. 0.7.1 + nuxt3

### ISSUE THREAD

**Issue by andysay** [unjs/h3#87]
in template vue 
```

    const data = await useAsyncData("blogitem", () =>
      $fetch("/api/news-item?", {
        method: "GET",
        params: {
          query: "slug",
          slug: route.params.id,
        },
      })
    ).then((res) => {
      return res.data;
    });

```

in server api        

 let query = useQuery(req)   
console.log(query)

return this.. before woks fine.
<img width="486" alt="Снимок экрана 2022-04-08 в 12 34 50" src="https://user-images.githubusercontent.com/5610952/162411350-3d576a98-35f4-47e7-a8cf-841be562746e.png">

**Comment by danielroe** [comment]
I can't reproduce this (see [repro](https://stackblitz.com/edit/github-tts1hq?file=app.vue)), but it looks like there is no api route matching that path. (Note that it is not necessary to add `?` in the URL.)

 Would you open an issue on https://github.com/nuxt/framework with a reproduction?
