### ISSUE TITLE
Missing h3 playground on StackBlitz

### ISSUE THREAD

**Issue by uynilo9** [unjs/h3#879]
### Environment

StackBlitz

### Reproduction

![](https://github.com/user-attachments/assets/7a2d1e44-5428-4b59-a86e-c0a2a1b17914)

### Describe the bug

As the title, we're missing playground in project, where StackBlitz would prefer it to be.

Also, the "Play online " in the official docs is invalid since it points to StackBlitz.
![](https://github.com/user-attachments/assets/15fcff98-5d10-4a28-8363-56c384f5c849)

**Comment by pi0** [comment]
fixed
