### ISSUE TITLE
Using `readBody` with Nuxt internal routing fails to parse URLSearchParams

### ISSUE THREAD

**Issue by phoenix-ru** [unjs/h3#887]
### Environment

- Operating System: `Linux`
- Node Version:     `v22.5.1`
- Nuxt Version:     `3.13.2`
- CLI Version:      `3.13.2`
- Nitro Version:    `2.9.7`
- Package Manager:  `npm@10.8.2`
- Builder:          `-`
- User Config:      `compatibilityDate`, `devtools`
- Runtime Modules:  `-`
- Build Modules:    `-`

### Reproduction

https://github.com/phoenix-ru/h3-urlsearchparams-reproduction

### Describe the bug

Users of `@sidebase/nuxt-auth` are experiencing the following problem with our module, described [here](https://github.com/sidebase/nuxt-auth/issues/883):
```
ERROR  [nuxt] [request error] [unhandled] [500] The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of URLSearchParams
```

We managed to pinpoint the problem to this piece of code:
https://github.com/sidebase/nuxt-auth/blob/a0704470583c5fea47c26c14b8673f8bb6a39a5f/src/runtime/composables/authjs/useAuth.ts#L120-L133

It works well when being called using HTTP, but fails when calling Nuxt endpoints from within a server. As you know,`$fetch` calls are translated to function calls in server code.

Upon some investigation, I was able to find the exact culprit - it is the `readRawBody` method and its `Buffer.from` return statement:
https://github.com/unjs/h3/blob/112fa338ef5bbde6207f3317d2ef51f0e52a59fa/src/utils/body.ts#L93

This is what happens:
- during a regular HTTP call it looks like `$fetch` serializes `URLSearchParams` and is therefore capable to deserialize them later;
- this doesn't happen during a function call - `readRawBody` receives `URLSearchParams` as-is;
- `URLSearchParams` successfully evades all the `if` checks and ends up in the last return statement.

I fixed it locally and verified the patch, I will submit a PR shortly.

**Comment by pi0** [comment]
fixed on edge and next release thanks.
