### ISSUE TITLE
[Bug][TS] Cannot return typed response via defineEventHandler

### ISSUE THREAD

**Issue by Rigo-m** [unjs/h3#89]
See type error [here](https://stackblitz.com/edit/github-t2n64t-rtntkj?file=server%2Fapi%2Ftest.ts)

**Comment by Rigo-m** [comment]
@pi0 was trying to migrate from `defineHandler`, could you help?

**Comment by pi0** [comment]
Should be solved in the last release.

**Comment by chrisxvin** [comment]
Still same error with 0.7.4

**Comment by chrisxvin** [comment]
It seems cannot assign object array to H3Response type.
ts(2345): Cannot assign "IMyInterface" to type "string | number | boolean"
