### ISSUE TITLE
How to stream files

### ISSUE THREAD

**Issue by maciej-jezierski** [unjs/h3#93]
Hi, I am trying to stream files from local disc (for a reason it's not served as static).

I tried to use sendStream or send it directly to pipe but each time I get 404. Documentation is not mentioning too much how to use streams. How to use it correctly with h3?

```
export default defineEventHandler((event) -> 
     const stream = fs.createReadStream(path);
     stream.pipe(event.res);
)
```

or 

```
const stream = fs.createReadStream(path);
      sendStream(event, stream);
```

**Comment by maciej-jezierski** [comment]
I found solution by using playground and checking code. Solution is super simple, sendStream has to be returned directly 

```
const r = "/path/to/file
return sendStream(event, fs.createReadStream(r))
```

In my case if you have promise first it's working as well

```
return $fetch(apiUrl, { method: "GET", parseResponse: JSON.parse }).
    .then(r => sendStream(event, fs.createReadStream(r.path)))
```

KISS, but generally would be good to add it to documentation before some other people run into this issue as streaming files is common exercise.

**Comment by Atinux** [comment]
Would love to see a PR to https://v3.nuxtjs.org/guide/features/server-routes#handling-requests-with-body to add an example about it 💚

**Comment by maciej-jezierski** [comment]
@Atinux I've even prepared code for h3 Readme.md and Nuxt repo as well with samples, but apparently I have some access problem. Will try to push it later.

**Comment by maciej-jezierski** [comment]
Nuxt PR: https://github.com/nuxt/framework/pull/4401

**Comment by pi0** [comment]
@Atinux We should probably start adding examples directly to h3 docs. Otherwise, we will end up with fragmented documentation and outdated info for utils. Also, consider `sendStream` support is not universal yet.

**Comment by manuel-84** [comment]
how to stream text from a variable and not in a file?
