### ISSUE TITLE
How to get body and params and other without composables (res.params, res.body)

### ISSUE THREAD

**Issue by Makkalay** [unjs/h3#934]
### Environment

Node 20
h3 last

### Reproduction

res.body are undefined

### Describe the bug

How to get body and params and other without composables (res.params, res.body).
Or to get event, context and read from them if i have only res (I can use node res.end but not res.send)?

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modify the NodeResponseProxy class to include references to the original H3Event and its properties, allowing access to request body, parameters, and other event-related information through the response object.

You can review changes in this commit: https://github.com/wwqwq2313/unjs-h3-934/commit/85c46586fc752dc88a29679a7c624067f89e6823.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Makkalay** [comment]
@wwqwq2313 a ha ha ha
@pi0 what you think?
