### ISSUE TITLE
What wildcard to write to execute middleware on all routes

### ISSUE THREAD

**Issue by Makkalay** [unjs/h3#935]
### Environment

last

### Reproduction

h3App.router.use(
            '**', // what to put to catch all routes?
            defineEventHandler((event) => {
                console.log("Middleware 1");
            }),
);

because `h3App.use()` no effect.

### Describe the bug

What wildcard to use to match all routes, npt work .*, *, **, .(*)

**Comment by Makkalay** [comment]
[When middleware will be](https://github.com/nuxt/nuxt/issues/14177#issuecomment-1556426767)

**Comment by Makkalay** [comment]
is not an object (evaluating 'p.replace')


 8 |  const ctx = {
 9 |     options,
10 |     rootNode: createRadixNode(),
11 |     staticRoutesMap: {}
12 |   };
13 |   const normalizeTrailingSlash = (p) => options.strictTrailingSlash ? p : p.replace(/\/$/, "") || "/";

**Comment by Makkalay** [comment]
@pi @danielroe @DamianGlowala  :( :( :( :(

**Comment by Makkalay** [comment]
Yah, that work wor all path not only `/`

```
h3App.stack.unshift({
            route: '/',
            handler: args[1],
})
```

**Comment by Makkalay** [comment]
Yah, that work for all routes, not only '/' as I think.

```
h3App.stack.unshift({
            route: '/',
            handler: handler,
})
```

**Comment by danielroe** [comment]
please stop trying to ping maintainers. adding a post (now deleted) mentioning three of us twenty minutes after posting it is... possibly a bit too much 

it's a Saturday, and this time of year many people are also taking holiday

rest assured your issue won't be ignored 

please in future update your issue by editing it with new relevant information - that would be a great help 🙏

**Comment by Makkalay** [comment]
I am happy what you are in the mood for parties
